libbpf/libbpf-rs

Cargo.lock, libbpf-rs/Cargo.toml, libbpf-rs/src/map.rs, libbpf-rs/src/program.rs
Useful for display prog/map types.
=> libbpf-rs: Derive Display trait for enums

Cargo.lock, examples/query/src/main.rs, libbpf-rs/Cargo.toml, libbpf-rs/src/query.rs
=> Support links in query API

libbpf-rs/src/map.rs, libbpf-rs/src/object.rs, libbpf-rs/src/program.rs, libbpf-rs/src/util.rs, libbpf-rs/tests/test.rs
Pinning/unpinning maps/progs is useful for networking applications.
=> libbpf-rs: Add pin/unpin API to Map/Program

examples/runqslower/src/main.rs
Do this where possible to make code more terse.
=> runqslower: Run Result<()> from main instead of unwrapping

libbpf-cargo/src/gen.rs, libbpf-rs/src/object.rs
See individual commits for details.
=> Minor API fixes

libbpf-rs/src/object.rs
If an `OpenObject` is created but not loaded, resources may leak.
Fix this by creating implementing Drop for `struct bpf_object *` but
disabling if object successfully loads.
Reported-By: Matt Mullins <mmullins@fb.com>
=> libbpf-rs: Prevent OpenObject from leaking resources if not `load()`ed

libbpf-cargo/src/lib.rs
=> libbpf-cargo: Add dummy library

libbpf-cargo/src/gen.rs
More reliable in general, especially in environments where build
artifacts may be cached and absolute paths introduce nondeterminism.
=> libbpf-cargo: gen: Embed object file as a literal array

libbpf-rs/src/perf_buffer.rs
Before, we didn't retain callback type information in CbStruct. That
meant when we called Box::from_raw() anything could have happened
(segfault, memory leak, etc.).
This commit reworks the callback storing bits to store fat pointers
instead of templated types for all the callbacks. The fat pointers store
the type information such that rust can recover the type information at
runtime. This also simplifies the code a bit.
This fixes #71.
=> libbpf-rs: Retain type information for CbStruct

libbpf-rs/src/program.rs
Several functions in program.rs were not handling cstrings correctly. This caused some headaches in my project due to strings not being null-terminated. I ended up null terminating them myself as a workaround, but this is obviously far from ideal. To fix this, I've updated all the offending functions to use `xxx_to_cstring` helper functions exposed in util.rs.
I also noticed that `T` in `attach_uprobe` really should be an `AsRef<Path>`, not an `AsRef<str>`. Fixed this as well.
=> libbpf-rs: Fix handling of cstrings in several functions

Cargo.lock, libbpf-cargo/Cargo.toml, libbpf-rs/Cargo.toml
Bump semver to 1.0 and nix to 0.21
=> Bump versions for semver and nix

libbpf-cargo/src/btf/btf.rs, libbpf-cargo/src/test.rs
The following code causes `SkeltonBuilder` to emit invalid Rust because it doesn't define `struct foo`:
**src/sample.bpf.c**
```
struct foo {
int x;
};
const volatile struct foo array[1] = { {0} };
```
**build.rs**
```
use libbpf_cargo::SkeletonBuilder;
fn main() {
SkeletonBuilder::new("src/sample.bpf.c")
.debug(true)
.generate("src/sample_skel.rs")
.unwrap();
}
```
Build output:
```
$ cargo build
Compiling libbpf-cargo v0.9.2 (/home/ben/scratch/libbpf-rs/libbpf-cargo)
Compiling example-broken v0.1.0 (/home/ben/scratch/libbpf-rs/example-broken)
error[E0412]: cannot find type `foo` in this scope
--> src/sample_skel.rs:65:19
|
65 |         pub bar: [foo; 1],
|                   ^^^ not found in this scope
For more information about this error, try `rustc --explain E0412`.
error: could not …
```
=> Emit type declarations for structs in global array variables.

libbpf-rs/src/perf_buffer.rs
Currently callbacks passed to PerfBuilder are assumed to have the
'static lifetime, which makes them hard to use.
A simple example based on the runqslower: let's say we want to store
events in a hashmap instead of printing them. We can't pass a mutable
reference to a hashmap into a closure and use the closure as a
sample_cb callback without giving an ownership with a "move" keyword.
But then we can't use the map afterwards.
Actually, handlers lifetime should be bound to the lifetime of
PerfBuffer object. Once it's gone, we don't need callbacks anymore.
After this change the following code can work:
let mut hm = HashMap::new();
{
let perf = PerfBufferBuilder::new(skel.maps_mut().events())
.sample_cb(|cpu: i32, data: &[u8]| { handle_event(&mut hm, cpu, data); })
.lost_cb(handle_lost_events) …
=> libbpf-rs: Fix PerfBuilder callbacks lifetime definition

libbpf-cargo/src/test.rs
=> Fix formatting for libbpf-cargo/src/test.rs

libbpf-rs/src/map.rs
…_fd to allow for non-pinned maps to be used
Signed-off-by: Yadunandan Pillai <ytpillai@pm.me>
=> Add reuse_fd function to allow non-pinned BPF maps to be reused

libbpf-cargo/src/gen.rs, libbpf-rs/src/object.rs, libbpf-rs/src/perf_buffer.rs, libbpf-rs/src/program.rs
* Add get_section_name function for Program
* Fix pages method for PerfBuffer
=> Minor fixe and addition

README.md
Quick docs update to use the latest dependency versions.
=> docs: update README to use latest crate versions

libbpf-rs/src/map.rs
=> libbpf-rs: Add new BPF map type definitions

libbpf-rs/src/program.rs
=> add getter and setter for bpf program flags

libbpf-rs/src/link.rs
Add wrapper for bpf_link__open, bpf_link__pin_path and bpf_link__detach.
Fixes #199
=> add functionality to bpf link api

.github/workflows/rust.yml
Signed-off-by: Joanne Koong <joannelkoong@gmail.com>
=> [github workflow] Update clang from clang-10 to clang-12

.github/workflows/rust.yml, libbpf-cargo/src/btf/btf.rs, libbpf-cargo/src/test.rs
Add a test case for BTF_KIND_FLOAT.
=> Add test for BTF_KIND_FLOAT

libbpf-rs/src/map.rs, libbpf-rs/tests/test.rs
libbpf-rs: add support for creating bpf map standalone(for resolving issue #191 )
Signed-off-by: zyy17 <zyylsxm@gmail.com>
=> libbpf-rs: add support for creating bpf map standalone

Cargo.lock, examples/bpf_query/Cargo.toml, examples/tc_port_whitelist/Cargo.toml, libbpf-rs/Cargo.toml
This decreases build time slightly.
=> Use nix 0.24, limit features

libbpf-rs/src/ringbuf.rs
Similar to #152 this makes the lifetime requirements for `RingBuffer` callbacks less strict. Currently they require `'static`, but they only need to live as long as the the `RingBuffer` object (they won't be called if the `RingBuffer` is gone).
=> ring buffer: less strict lifetime for callback

libbpf-rs/src/tc.rs
Various formatting and wording fixes.
=> Fix up more TcHook/TcHookBuilder docs

CONTRIBUTING.md, README.md
This is the first (and basic) version of the contributor's guide.
=> [Contributor's guide] Add doc for contributing to libbpf-rs

libbpf-cargo/src/btf/btf.rs
This makes sure that the type identifier contained in the array is constructed with a valid default.
Since we were hardcoding `::default()` after the type identifier, it was not working well with nested arrays
Example:
```
uint8_t pcomms[5][16];
```
Would fail because
```
[[u8; 16]::default(); 5]
```
is invalid.
This would turn the impl in:
```
[[u8::default; 16]; 5]
```
It's a fairly minor change that should not impact the majority of types
=> Used contained value's default for Arrays when implementing Default

libbpf-rs/src/ringbuf.rs
ringbuf: Allow poll() to block for an indefinite time period
ring_buffer__poll in libbpf internally calls epoll_wait. Specifying a
timeout of -1 to epoll_wait causes it to block indefinitely if no event
transpires. We should support this functionality in libbpf-rs as well.
In this change, if the user passes in Duration::MAX as the timeout, this
will cause the ringbuf poll to block indefinitely until an event occurs.
=> ringbuf: Allow poll() to block for an indefinite time period

.github/workflows/rust.yml, examples/capable/src/main.rs, libbpf-rs/src/error.rs, libbpf-rs/src/iter.rs, libbpf-rs/src/lib.rs, libbpf-rs/src/link.rs, libbpf-rs/src/map.rs, libbpf-rs/src/object.rs, libbpf-rs/src/perf_buffer.rs, libbpf-rs/src/print.rs, libbpf-rs/src/program.rs, libbpf-rs/src/query.rs, libbpf-rs/src/ringbuf.rs, libbpf-rs/src/tc.rs
=> Check documentation in CI

CONTRIBUTING.md
This change extends CONTRIBUTING.md with a bullet point that suggests the addition of tests for newly added features as well as bug fixes.
=> Suggest the addition of tests in CONTRIBUTING.md

libbpf-rs/src/map.rs, libbpf-rs/src/program.rs, libbpf-rs/tests/test.rs
motivation for this PR: I'm adding an option to my loader to check that **all** helpers in the program are supported by the kernel.
For this to work, i need to iterate the program instructions, get the called helpers and probe them.
To that end I have:
- added `insn` to OpenProgram (and for completeness, to Program too)
- added `prog_type` and `name` to OpenProgram
- Added a safe version libbpf probes in probe.rs
=> Add probes, and Program::insns

libbpf-cargo/src/gen.rs
Please see individual commits for description.
=> Make `rustfmt` dependency optional

.github/workflows/rust.yml
=> Enable test_btf_dump_float in CI

Cargo.lock, libbpf-cargo/Cargo.toml, libbpf-cargo/src/btf/btf.rs, libbpf-cargo/src/gen.rs, libbpf-rs/Cargo.toml, libbpf-rs/src/map.rs, libbpf-rs/src/object.rs, libbpf-rs/src/perf_buffer.rs, libbpf-rs/src/program.rs, libbpf-rs/src/ringbuf.rs, libbpf-rs/src/skeleton.rs, libbpf-rs/src/tc.rs, libbpf-rs/tests/test.rs
Update both libbpf-rs and libbpf-cargo to version 1.1.0
=> libbpf-rs, libbpf-cargo: Update to libbpf-sys v 1.1.0

.github/workflows/rust.yml, README.md, examples/capable/Cargo.toml, examples/tproxy/Cargo.toml, libbpf-cargo/Cargo.toml, libbpf-rs/Cargo.toml, libbpf-rs/src/print.rs
=> Add CI step to build against minimum version of dependencies

Cargo.lock, examples/bpf_query/Cargo.toml, examples/tc_port_whitelist/Cargo.toml, examples/tproxy/Cargo.toml, libbpf-cargo/Cargo.toml, libbpf-rs/Cargo.toml
=> Update a few dependencies

.github/workflows/publish.yml, .github/workflows/test.yml
Here is a sample run: https://github.com/danielocfb/libbpf-rs/actions/runs/4088926223
=> Add GitHub Actions workflow to publish new versions

libbpf-rs/src/map.rs, libbpf-rs/src/object.rs
=> Expose underlying raw pointer in `Object` and `Map`

libbpf-rs/src/ringbuf.rs, libbpf-rs/tests/test.rs
Please see individual commits for description.
=> Loosen RingBuffer lifetime requirements

.github/workflows/test.yml, libbpf-rs/CHANGELOG.md, libbpf-rs/src/map.rs, libbpf-rs/src/program.rs
=> Fix 32 bit builds

libbpf-rs/src/query.rs
This is closing out a TODO from a previous commit
=> libbpf-rs: Replace size_of with size_of_val in query.rs

libbpf-rs/CHANGELOG.md
This change adds a CHANGELOG entry for #541.
=> Add CHANGELOG entry for #269

libbpf-rs/src/object.rs, libbpf-rs/tests/test.rs
This allows you to set a namespace for the automatically pined maps and things.
=> libbpf-rs: add pin_root_path interface to ObjectBuilder

libbpf-rs/CHANGELOG.md
This change adds a CHANGELOG entry for #545.
=> Add CHANGELOG entry for #545

libbpf-rs/CHANGELOG.md
Add a CHANGELOG entry for the changes made as part of #617.
=> Add CHANGELOG entry for #617

libbpf-rs/CHANGELOG.md, libbpf-rs/src/xdp.rs, libbpf-rs/tests/test_xdp.rs
Add a CHANGELOG entry for #625 and fix up various minor details.
=> Add CHANGELOG entry for #625

libbpf-rs/src/xdp.rs, libbpf-rs/tests/test_xdp.rs
=> add: replace support for xdp

libbpf-rs/CHANGELOG.md, libbpf-rs/tests/test_xdp.rs
Add a CHANGELOG entry for #647 and fix up some minor details.
=> Add CHANGELOG entry for #647

libbpf-rs/src/ringbuf.rs, libbpf-rs/tests/test.rs
When consuming items from a ring buffer we may want to get the exact amount of items consumed, instead of returning a simple success/failure result.
For this reason introduce new methods: raw_poll() and raw_consume() that will return the same return code (as i32) from libbpf.
This can be used either to check the amount of items consumed from the ring buffer but also to check for specific error numbers.
Thank you for considering a contribution!
In order to streamline review experience for contributors and reviewers, please
be sure to *read* and *follow* the [Contributor's Guide][cont-guide]. It
lays out basic best practices, which, if followed will reduce unnecessary back
and forth and, ultimately, minimize the time it takes to get your change into
the library.
[cont-guide]: …
=> RingBuffer: introduce raw_poll() and raw_consume()

libbpf-rs/CHANGELOG.md
Add a CHANGELOG entry for pull request #680.
=> Add CHANGELOG entry for #680

libbpf-rs/CHANGELOG.md
Add a CHANGELOG entry for pull request #687.
=> Add CHANGELOG entry for #687

libbpf-rs/src/program.rs, libbpf-rs/tests/test.rs
Fix some "issues" introduced as part of #692.
=> Clean up after #692

libbpf-cargo/src/gen/mod.rs
Dealing with strings for representing the internal map types supported is a bit of a pain.
Introduce the `InternalMapType` `enum` that makes those entities first class citizens in the code generation code.
=> libbpf-cargo: Make internal map type a first class entity

libbpf-cargo/src/gen/mod.rs, libbpf-rs/src/btf/mod.rs, libbpf-rs/src/object.rs
=> Use Btf::from_bpf_object() constructor in code generation code

libbpf-cargo/CHANGELOG.md, libbpf-cargo/src/gen/btf.rs, libbpf-cargo/src/test.rs, libbpf-rs/CHANGELOG.md, libbpf-rs/src/btf/types.rs
=> Add bitfield support

Cargo.lock, libbpf-rs/Cargo.toml, libbpf-rs/src/iter.rs, libbpf-rs/src/map.rs, libbpf-rs/src/query.rs, libbpf-rs/tests/test.rs
=> Remove nix dependency in libbpf-rs

libbpf-cargo/CHANGELOG.md, libbpf-cargo/src/gen/btf.rs, libbpf-cargo/src/test.rs
=> Correctly handle reserved identifiers

libbpf-cargo/src/gen/btf.rs
Make the `GenBtf::size_of()` method a free-standing function to make it more universally usable.
=> libbpf-cargo: Make GenBtf::size_of a free-standing function

libbpf-cargo/src/gen/btf.rs
Introduce the `AnonTypes` type, as a helper providing the means for naming otherwise anonymous BTF types. This is purely an internal refactoring, no change in semantics.
=> libbpf-cargo: Introduce AnonTypes abstraction

libbpf-cargo/src/gen/btf.rs
Factor out a new free-standing function, type_declaration(), that generates the Rust type declaration for a BTF type.
=> libbpf-cargo: Make type_declaration a free-standing function

libbpf-cargo/src/gen/btf.rs
Factor out a new free-standing function, required_padding(), that calculates the required padding for a type based on its inputs.
=> libbpf-cargo: Make required_padding a free-standing function

vmlinux/src/lib.rs
It turns out we don't have to go completely unsafe and work with pointers everywhere, given that the slice::split_first() method is const as well. Use it to simplify the code a bit and reduce the amount of unsafe logic.
=> vmlinux: Use less unsafe code

Cargo.lock, examples/bpf_query/src/main.rs, libbpf-rs/CHANGELOG.md, libbpf-rs/Cargo.toml, libbpf-rs/src/map.rs, libbpf-rs/src/program.rs
This reverts commit 341cb54f6ff66c941d9908a8e39c42519d1251f3.
=> Reapply "Remove strum_macros dependency"

examples/tcp_ca/src/main.rs
It turns out we don't really need to work with CStr objects in the tcp_ca example -- OsStr stuff should suffice. Switch everything over.
=> Switch tcp_ca example over to using OsStr

libbpf-rs/src/map.rs
Convert a bunch of private methods on the MapHandle into free-standing functions. Doing so will minimize the churn caused by follow on patches.
=> Make a bunch of private methods free-standing

libbpf-rs/tests/test.rs
With recent changes to using on-the-fly iteration of BPF maps we introduced a bunch of repeated boilerplate code in our integration tests. Shorten it somewhat by introducing the get_map() helper function.
=> Introduce get_map() helper function

libbpf-rs/tests/test.rs
With recent changes to using on-the-fly iteration of BPF program we introduced a bunch of repeated boilerplate code in our integration tests. Shorten it somewhat by introducing the get_prog() helper function.
=> Introduce get_prog() helper function

libbpf-rs/src/skeleton.rs
It appears we need the boxes because we effectively hand over ownership of the object to C code. This reverts commit 7a1e219b779a ("Remove a bunch of unnecessary (??) boxes").
=> Revert "Remove a bunch of unnecessary (??) boxes"

libbpf-cargo/src/gen/mod.rs, libbpf-rs/CHANGELOG.md, libbpf-rs/src/lib.rs, libbpf-rs/src/map.rs, libbpf-rs/src/object.rs, libbpf-rs/src/program.rs, libbpf-rs/tests/common/mod.rs, libbpf-rs/tests/test.rs, libbpf-rs/tests/test_tc.rs, libbpf-rs/tests/test_xdp.rs
=> Split `Map` & `Program` types into shared and exclusive variants

examples/capable/src/main.rs, examples/runqslower/src/main.rs, examples/tc_port_whitelist/src/main.rs, examples/tcp_ca/src/main.rs, examples/tcp_option/src/main.rs, examples/tproxy/src/main.rs, libbpf-cargo/CHANGELOG.md, libbpf-cargo/src/gen/mod.rs, libbpf-cargo/src/test.rs, libbpf-rs/src/link.rs, libbpf-rs/src/map.rs, libbpf-rs/src/object.rs, libbpf-rs/src/perf_buffer.rs, libbpf-rs/src/program.rs, libbpf-rs/src/skeleton.rs, libbpf-rs/tests/common/mod.rs, libbpf-rs/tests/test.rs, libbpf-rs/tests/test_tc.rs, libbpf-rs/tests/test_xdp.rs
=> Make maps and programs publicly accessible members in generated skeletons

libbpf-cargo/src/gen/mod.rs
The usage of raw strings is only marginally beneficial: it means we no longer have to escape string literals inside. However, we already have to escape the much more prevalent curly braces.
Switch to using regular strings, which provide us with more control over the insertion of newline characters into the generated code. Doing so helps us eliminate some weird looking empty lines in the resulting skeletons.
=> libbpf-cargo: Stop using raw strings

libbpf-cargo/src/gen/mod.rs, libbpf-cargo/src/test.rs
Our skeleton generation code instantiates a new GenBtf object in many of the individual sub-steps of the generation procedure. However, that is a broken pattern: each GenBtf instance starts the counter that determines numbering of Rust types generated for anonymous C types anew and, hence, we can run into duplicate names.
This change fixes the issue by using a "global" GenBtf instance instead.
=> libbpf-cargo: Fix generation of duplicate anon types

libbpf-cargo/src/gen/mod.rs
Our generated struct_ops types are somewhat special in that we replace some void* pointers with more appropriately typed ones. As such, we should make sure to generate struct_ops types before any other ones, to ensure that the correct variant is being emitted.
=> libbpf-cargo: Generate struct_ops types first

libbpf-cargo/src/test.rs
Our libbpf-cargo skeleton compilation tests duplicate hundreds of lines of code.
Start factoring out a helper function, build_rust_project_from_bpf_c(), to de-duplicate some of the mess.
=> Introduce build_rust_project_from_bpf_c() test helper function

libbpf-cargo/src/test.rs
=> Stop using tabs in test code

libbpf-rs/src/program.rs, libbpf-rs/tests/test.rs
Content of this field may change by using some programs (like `syscall`)
Fix #888
=> Make mutable ProgramInput.context_in

Cargo.lock, examples/capable/Cargo.toml, examples/runqslower/Cargo.toml, examples/tc_port_whitelist/Cargo.toml, examples/tcp_ca/Cargo.toml, examples/tcp_option/Cargo.toml, examples/tproxy/Cargo.toml, libbpf-cargo/Cargo.toml, libbpf-cargo/src/test.rs, libbpf-rs/dev/Cargo.toml
Update the vmlinux.h header stuff to Linux version 6.6.
=> Update vmlinux.h headers to 6.6

libbpf-rs/src/perf_buffer.rs
We use some helper traits inside the perf_buffer module to work around the non-stability of trait aliases. However, currently these helpers don't appear correctly in the documentation, rendering the documentation for everything using rather...useless.
Expose these traits publicly so that they are resolved properly inside the documentation.
=> Fix documentation for PerfBufferBuilder callback types

libbpf-cargo/CHANGELOG.md, libbpf-cargo/src/gen/btf.rs, libbpf-cargo/src/test.rs, libbpf-rs/CHANGELOG.md, libbpf-rs/src/btf/mod.rs, libbpf-rs/src/btf/types.rs
=> Fix skeleton generation for enum64 types

libbpf-cargo/src/test.rs
Stop using `NamedTempFile` unnecessarily in tests that already have a temporary directory that they use for the Rust project. Just create the skeleton at a fixed location relative to said project, to make it easier to inspect this kind of stuff for debugging purposes.
=> libbpf-cargo: Stop using `NamedTempFile` unnecessarily

libbpf-rs/src/program.rs
Previously, we use if/else to call the same libbpf API
with different params (null or non-null). This is a bit
cumbersome. Let's make it more idiomatic and succinct.
No functional changes intended.
=> libbpf-rs: Unify calls to libbpf APIs

libbpf-rs/tests/common/mod.rs
As report in #1110, it seems like the current implementation
of symbol resolve is incorrect. Fix it in BCC way.
=> libbpf-rs: Fix get_symbol_offset() in test code

.clang-format, libbpf-rs/tests/bin/src/ksyscall.bpf.c, libbpf-rs/tests/bin/src/map_auto_pin.bpf.c, libbpf-rs/tests/bin/src/mapiter.bpf.c, libbpf-rs/tests/bin/src/netfilter.bpf.c, libbpf-rs/tests/bin/src/percpu_map.bpf.c, libbpf-rs/tests/bin/src/ringbuf.bpf.c, libbpf-rs/tests/bin/src/run_prog.bpf.c, libbpf-rs/tests/bin/src/runqslower.bpf.c, libbpf-rs/tests/bin/src/taskiter.bpf.c, libbpf-rs/tests/bin/src/tc-unit.bpf.c, libbpf-rs/tests/bin/src/tracepoint.bpf.c, libbpf-rs/tests/bin/src/uprobe.bpf.c, libbpf-rs/tests/bin/src/usdt.bpf.c, libbpf-rs/tests/bin/src/xdp.bpf.c
Format the test code with:
```
clang-format -i libbpf-rs/tests/bin/src/*
```
=> libbpf-rs: Format BPF test codes

Cargo.lock, examples/netfilter_blocklist/Cargo.toml, examples/netfilter_blocklist/src/bpf/netfilter_blocklist.bpf.c
See https://github.com/libbpf/vmlinux.h/pull/7
=> examples: update netfilter_blocklist for newer vmlinux.h
