libbpf/libbpf-rs

- example/src/main.rs
- libbpf-rs/src/perf_buffer.rs
This allows PerfBufferBuilder to build when the user does not specify
one of the callbacks, because there is no longer any ambiguity about
function type to infer if one is missing.
The mutators also now have to modify the type, as they replace the
callback function type on-demand -- they now take self by move, and
return a new PerfBufferBuilder with the right types.
> PerfBufferBuilder: use concrete types for ::new

- libbpf-rs/src/error.rs
- libbpf-rs/src/perf_buffer.rs
There was a bunch before. I think we can cover all the cases with just 3
without losing much context:
* Error::System variant for syscall or syscall-like operation failures
* Error::InvalidInput for invalid input into libbpf-rs
* Error::Internal for internal non-recoverable errors
> libbpf-rs: Slim down number of error variants

- libbpf-rs/src/lib.rs
- libbpf-rs/src/query.rs
This commit implements an iterator for prog, map, and btf information.
The code was all pretty similar so I used a `macro_rules!` to generate
it. This makes it easy to add new iterators if libbpf (the C library)
follows the same convention for future query APIs.
> libbpf-rs: Implement query API

- libbpf-rs/src/map.rs
- libbpf-rs/src/perf_buffer.rs
- libbpf-rs/src/program.rs
- libbpf-rs/src/query.rs
- libbpf-rs/src/util.rs
In several places, we use a Rust type of `u64` to represent a C type that is actually pointer sized. This causes compilation errors when targeting 32-bit platforms. Similarly, we assume that `std::os::raw::c_char` is an `i8`, when in fact it can be either an `i8` or a `u8` depending on the platform we're targeting. Fix this by adding casts and using the `usize` Rust type where appropriate.
I don't claim that this commit fixes all such issues, but it does at least fix the ones that were preventing us from building for 32-bit ARM with musl libc. I have also confirmed that it does not regress compilation of a simple demo program on x86_64.
> Don't assume the width and signedness of C types

- libbpf-rs/src/query.rs
The `bpf_obj_get_info_by_fd()` function is used to retrieve information about a BPF object. This is done by passing the provided buffer straight down through the `bpf()` syscall so the kernel can fill it in. However, new members are regularly added to the end of the info structs, which means that old kernels may not fill every member. When this happens, the kernel will fill in the bytes it knows about and leave the rest unchanged. However, it will only do this after [verifying][1] that the entire buffer is zeroed. If the buffer isn't zeroed, it will assume we're trying to use an extension it doesn't support and fail with `E2BIG`.
We currently use Rust's `::default()` to initialize the struct we ask the kernel to fill. Although the default values of all the numeric types in the struct are …
> Ensure buffer for bpf_obj_get_info_by_fd() is fully zeroed

- libbpf-cargo/src/main.rs
docs.rs doesn't seem to generate documentation for non-library crates.
So the next best option is to provide the documentation in the --help
menus.
> cargo-libbpf: Move docs to --help

- libbpf-rs/src/program.rs
This is required to support verdict/parser of SK_SKB programs. The programs must be attached to SOCKMAP/SOCKHASH for them to work.
References:
- https://lwn.net/Articles/731133/
- https://blog.cloudflare.com/sockmap-tcp-splicing-of-the-future/
- https://blog.bolcsfoldi.com/posts/ebpf-sockmap/
> libbpf-rs: add attach_sockmap for Program

- libbpf-rs/src/program.rs
bpf_prog_attach() has the following code path:
bpf_prog_attach(..)
bpf_prog_attach_xattr(..)
sys_bpf(..)
syscall(__NR_bpf, ..)
syscall(2) returns -1 on error and stores errno in `errno`. So I think
we need to explicitly get errno() for attach_sockmap().
> libbpf-rs: Return correct errno for attach_sockmap

- README.md
Rustdoc doesn't generate docs for binary crates
> Remove docs link for `libbpf-cago`

- libbpf-cargo/src/gen.rs
- libbpf-rs/src/program.rs
libbpf returns ESRCH if the program cannot be autoattached. Instead of
erroring out, let's ignore that specific failure.
Codegen diff: http://ix.io/2GhS
> Do not bail on un-auto-attachable program attachment

- examples/runqslower/README.md
- libbpf-cargo/src/main.rs
- libbpf-cargo/src/make.rs
The `cargo libbpf make` subcommand runs:
* cargo libbpf build
* cargo libbpf gen
* cargo build
in sequence, bailing at the first error. The idea is to help prevent
users from forgetting a step. If a step is forgotten, the end results
are unpredictable.
> cargo-libbpf: make: Add `make` subcommand 

- examples/runqslower/src/main.rs
- libbpf-cargo/src/gen.rs
We already expose `obj_builder` member in SkelBuilder, so no need to
generate unnecessary code.
> libbpf-cargo: gen: Remove ObjectBuilder options in skeleton builder

- libbpf-rs/src/skeleton.rs
If more fields are added to the libbpf structs and we don't notice, we
want to make sure they're zeroed.
> libbpf-rs: skeleton: alloc_zeroed() instead of alloc()

- libbpf-rs/src/skeleton.rs
This change allows BPF programs without maps.
> BPF programs will not run unless there is a map existing.

- Cargo.lock
- examples/runqslower/src/bpf/runqslower.bpf.c
- examples/runqslower/src/main.rs
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/btf/c_types.rs
- libbpf-cargo/src/btf/mod.rs
- libbpf-cargo/src/btf/types.rs
- libbpf-cargo/src/gen.rs
- libbpf-cargo/src/main.rs
- libbpf-cargo/src/test.rs
- libbpf-rs/Cargo.toml
This PR adds support for mmap'd datasec fields. Userspace can now
share data with progs via simple variable reads/writes. See the final
commit for the user facing interface.
See individual commits for details.
> libbpf-cargo: gen: Add datasec mmap support

- libbpf-cargo/src/gen.rs
- libbpf-cargo/src/main.rs
- libbpf-cargo/src/make.rs
Generates and prints the skeleton to stdout for a given object file.
This is useful for integrating with non-cargo build systems.
> libbpf-cargo: gen: Add --object option for standalone skel generation

- Cargo.lock
- libbpf-rs/Cargo.toml
- libbpf-rs/src/map.rs
- libbpf-rs/tests/test.rs
Useful for interacting with pinned maps.
This closes #52.
> libbpf-rs: Add OpenMap::reuse_map() API

- libbpf-rs/src/map.rs
- libbpf-rs/tests/test.rs
Add iterator over keys in a map. This provides the user a way to iterate
over the keys in a map.
Note it was a deliberate decision to _not_ provide map values.  The
reason is that we can race between getting the key and the prog deleting
the entry in the map. It's difficult to propagate this error so let the
user handle it instead.
This closes #53.
> libbpf-rs: Add Map::keys() iterator

- libbpf-cargo/src/gen.rs
When we opened the object file to generate the skeleton, we used `{name}`.
The generated skeleton then opens the object with `{name}_bpf`. Since
libbpf uses the object name to derive the map/prog names, this skew can
cause issues.
The issue is sometimes covered up by the fact that libbpf truncates the
object name to a certain number of characters. So for longer object
names, this issue doesn't show up. For shorter object names, this issue
occurs.
This closes #57 .
> libbpf-cargo: gen: Fix skeletons with short object names

- examples/runqslower/src/bpf/runqslower.bpf.c
- examples/runqslower/src/bpf/runqslower.h
- examples/runqslower/src/main.rs
- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/test.rs
It's better to define a type in one place so things don't get out of
sync.
> runqslower: Don't redefine `struct event` in rust code

- .github/workflows/rust.yml
I guess there was an OS update and it was installing the "alternatives"
thing into /bin/clang.
> build: Remove symlink step

- libbpf-cargo/src/gen.rs
Recently, I wanted to do something like the following to encapsulate program opening and loading logic within a single function in my project.
```rust
fn open_and_load<'a>(debug: bool) -> Result<ProgSkel<'a>> {
let mut builder = ProgSkelBuilder::default();
builder.obj_builder.debug(debug);
bump_memlock_rlimit().context("Failed to bump rlimit")?;
let open_skel = builder.open().context("Failed to open skeleton")?;
let mut skel = open_skel.load().context("Failed to load BPF objects")?;
skel.attach()
.context("Failed to attach BPF objects to events")?;
Ok(skel)
}
```
However, the borrow checker would complain under the current code generation logic, wherein the builder's open() method takes a mutable reference to self.
This pull request fixes this behaviour by changing the generated open() …
> Change generated builder's open() method to consume self

- libbpf-cargo/src/gen.rs
Old error:
```
$ cargo libbpf gen --rustfmt-path /bin/asdf
Warning: unrecognized map: .maps
Warning: unrecognized map: license
Failed to generate skeleton for /home/daniel/dev/libbpf-rs/examples/runqslower/src/bpf/runqslower.bpf.c: No such file or directory (os error 2)
```
New error:
```
$ cargo libbpf gen --rustfmt-path /bin/asdf
Warning: unrecognized map: .maps
Warning: unrecognized map: license
Failed to generate skeleton for /home/daniel/dev/libbpf-rs/examples/runqslower/src/bpf/runqslower.bpf.c: Failed to spawn rustfmt
```
This closes #68.
> libbpf-cargo: gen: Improve error message when missing rustfmt

- libbpf-rs/src/perf_buffer.rs
The function `fn is_power_two` in `perf_buffer.rs` don't work as expected (It works in C++ though).
This PR fixes that and add a small test.
> libbpf-rs: Fix is_power_two implementation

- libbpf-cargo/src/gen.rs
When I run `libbpf make` task to generate a rust code, 
I found `non_camel_case_type` warning. This PR is to resolve the warning.
> libbpf-cargo/gen: convert snake_case to camel case to resolve non_camel_case_type warning

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/gen.rs
- libbpf-cargo/src/metadata.rs
- libbpf-rs/src/skeleton.rs
@danobi I took a quick stab at getting rid of all warnings.
There were a bunch of errors in [`examples/runqslower`](https://github.com/libbpf/libbpf-rs/tree/master/examples/runqslower), but it didn't quite make sense to add Clippy ignore's in there, since people are likely going to copy/paste from that code. Let me know if I got that wrong.
Otherwise, this is pretty much my first Rust code ever, so let me know what I should fix!
> Fix clippy warnings

- libbpf-cargo/Cargo.toml
- libbpf-rs/Cargo.toml
Bump versions for `vsprintf` and `libbpf-sys`. Needed for the Fedora packaging (see https://bugzilla.redhat.com/show_bug.cgi?id=1958352)
> cargo: update version pins

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/btf/types.rs
- libbpf-cargo/src/test.rs
Anonymous structs and unions cannot be used in a libbpf-rs project as the structs and unions are not named.
Name anonymous structs as "anon_struct_X" where X is an increasing integer, and anonymous unions as "anon_union_X"
> Allow usage of anonymous structs and unions

- libbpf-cargo/src/gen.rs
- libbpf-rs/src/object.rs
- libbpf-rs/src/util.rs
- libbpf-rs/tests/test.rs
I want to be able to easily iterate over all BPF programs and maps in my libbpf_rs project. My use case is for easy pinning/unpinning but I imagine this capability could be useful for other use cases as well.
This PR implements `progs_iter` and `maps_iter` for `OpenObject` and `Object` to address this use case. It also adds a simple smoke test and some documentation for previously undocumented getters.
Fixes #77 Closes #79
> Implement progs_iter and maps_iter for Object and OpenObject

- Cargo.lock
- examples/runqslower/.gitignore
- examples/runqslower/Cargo.toml
- examples/runqslower/README.md
- examples/runqslower/build.rs
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/build.rs
- libbpf-cargo/src/gen.rs
- libbpf-cargo/src/lib.rs
- libbpf-cargo/src/main.rs
- libbpf-cargo/src/make.rs
- libbpf-cargo/src/test.rs
- libbpf-rs/src/lib.rs
Build scripts are pretty standard for projects that have a codegen step
as part of the build. The current method is kind of strange (took a
while to realize) where we have the user run a custom cargo tool. It'd
be nicer to give users the option to encapsulate everything in a build
script such that `cargo build` "just works".
See 4th commit in series for how runqslower example looks with the
build script.
This closes #63.
> libbpf-cargo: Add SkeletonBuilder library for use in build scripts

- libbpf-cargo/src/build.rs
- libbpf-cargo/src/lib.rs
- libbpf-cargo/src/main.rs
- libbpf-cargo/src/make.rs
- libbpf-cargo/src/test.rs
More likely to work on different systems. I think the tests were
originally hardcoded b/c the CI had a fixed symlink at /bin/clang.
> libbpf-cargo: tests: Use clang from $PATH

- examples/runqslower/.gitignore
- examples/runqslower/build.rs
- examples/runqslower/src/main.rs
In line with how libbpf-bootstrap and libbpf-tools does it.
> runqslower: Place generated skeleton in .output directory

- libbpf-rs/src/program.rs
My original CStrings fix had a really bad lifetime issue that caused a use-after-free error.
The details are outlined here: https://doc.rust-lang.org/std/ffi/struct.CString.html#method.as_ptr
Update affected functions to store the CString and raw pointer as separate bindings to prevent the early free.
> libbpf-rs/program.rs: Fix lifetime issue with CString pointers

- examples/runqslower/src/main.rs
- libbpf-cargo/src/gen.rs
- libbpf-cargo/src/test.rs
- libbpf-rs/src/object.rs
- libbpf-rs/tests/test.rs
This is a draft proposal to refactor existing Object and OpenObject getters into mutable and immutable variants. It is based on top of my PR for maps and program iterators and should not be landed until that is merged. Existing getters are renamed with the `_mut` suffix and new getters are created for the immutable variants, using the original names. For now, libbpf-cargo/gen.rs has been changed to emit `xxx_unwrap_mut()` instead of `xxx_unwrap()`.
I have a couple of points that I'd like to discuss before making any further progress on this.
1. We should probably add mutable/immutable variants to the generated skeleton in addition to Object and OpenObject.
- As I see it, this could be done in one of two ways. Either add an extra struct like MapsMut that would be accessed using something …
> libbpf-rs: Add immutable getters

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/test.rs
Compilation breaks when enums are used in structures.  Enums cannot be #[derive(Default)], so in order to conform to using Defaults with structures we must impl default for Enums.
Advanced Rust style enums (enums that act as unions, or hold different types) have not been considered as C-BPF will not use these advanced Rust style enums.
Alternate implementation to this is to force the programmer to impl Default themselves.  This gives a bad experience when using libbpf-cargo+libbpf-rs as compilation will break if using something like cargo libbpf make, and the impl Default must constantly be edited whenever the C-BPF enum is changed.
Default value used is the first value within the enum.
> [libbpf-cargo] Add an impl Default for enums

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/test.rs
This PR modifies libbpf-cargo so that it no longer generates skeleton code which will fail to compile
due to the array size limitation of #[derive(Default)].
Determine if a structure contains an array longer than 32. If it does, output both the structure definition
and also an impl Default for the structure. If a structure does not contain an array longer than 32 use #[derive(Default)]
for output
This is a continuation of https://github.com/libbpf/libbpf-rs/pull/87. as branch long_arrays got corrupted and I wasn't able
to properly rebase.
Addresses: https://github.com/libbpf/libbpf-rs/issues/78
> If an array has length > 32, #[derive(Default)] will fail to compile.

- libbpf-rs/src/link.rs
Add the ability to "disconnect" a BPF Link to prevent the underlying program from being detached when the Link is dropped.
> libbpf-rs/link.rs: Add Link::disconnect()

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/gen.rs
libbpf-cargo was making assumptions about the width of c_ulong and signedness of c_char in some places. This was causing compilation to fail on some other archs. Fixes #108
> libbpf-cargo: Fix compilation on non-x86_64 archs

- Cargo.lock
- libbpf-cargo/Cargo.toml
Needed to package `libbpf-cargo` in Fedora
> libbpf-cargo: bump cargo_metadata to 0.12

- Cargo.lock
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/gen.rs
- libbpf-cargo/src/test.rs
According to [this security advisory](https://rustsec.org/advisories/RUSTSEC-2020-0077), the `memmap` crate is no longer maintained and should be replaced with the `memmap2` fork. This causes `cargo audit` to fail on any project that depends on `libbpf-cargo`. This PR simply replaces `memmap` with `memmap2`.
As an aside, I would like to propose adding `cargo audit` and `cargo clippy` to the CI workflow to reduce the risk of vulnerable dependencies and enforce good code hygiene. Any thoughts? I can file a separate PR for this if you're interested.
> libbpf-cargo: Switch memmap dependency to memmap2

- Cargo.lock
- libbpf-rs/Cargo.toml
Hi,
I'd like to update strum_macros to 0.21, as we strive to keep package in sync to the latest version during Fedora Rust packaging.
> Bump strum_macros to 0.21

- libbpf-cargo/src/test.rs
Remove Boiler plate code in btf tests
Addresses issue #88
https://github.com/libbpf/libbpf-rs/issues/88
This change edits all current btf generation tests
to make them more streamlined and easier to read
future tests will be easier to implement as boiler plate code is
taken care of by the two functions and one macro
- build_bpf_prog (build a Btf structure from a given source text)
- assert_defition (assert that output of a given source text
matches expected output)
- assert_type! (assert that a single Btf type of given name exists
in a Btf structure, return the type_id to that named Btf type)
Pros:
- lots of boiler plate has been dealt with
- can left align C-BPF code and left align expected generated Rust code
without worrying about newlines at start or end of String
- do not need to use …
> Remove Boiler plate code in btf tests

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/test.rs
Fix for 
https://github.com/libbpf/libbpf-rs/issues/119
Rust cannot #[derive(Debug)] for unions.  Structures must have Debuggable unions in order to #[derive(Debug)] for them.
To solve issue #119 we must either remove all #[derive(Debug)] or impl Debug for unions.  This PR suggests doing the latter.
> Add a Debug impl for all union types

- libbpf-cargo/src/build.rs
I couldn't get all the tests to pass, but I think this should fix some issues:
Truncated `cargo test`:
```
running 20 tests
test test_object_build_from_memory ... ok
test test_object_name ... ok
test test_object_ringbuf ... ok
test test_object_ringbuf_closure ... ok
test test_object_maps_iter ... ok
test test_object_programs_iter_mut ... ok
test test_object_map_mutation ... ok
test test_object_map_empty_lookup ... ok
test test_object_map_lookup_flags ... ok
test test_object_map_pin ... FAILED
test test_object_link_pin ... FAILED
test test_object_build_and_load ... ok
test test_object_map_key_iter_empty ... ok
test test_object_map_key_iter ... ok
test test_object_programs ... ok
test test_object_maps ... ok
test test_object_map_key_value_size ... ok
test test_object_reuse_pined_map ... …
```
> Use proper iterator on libbpf-cargo build

- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/build.rs
- libbpf-rs/Cargo.toml
Re-export libbpf-sys's novendor feature. When used turned on, libbpf-rs
and libbpf-cargo will avoid vendoring libbpf and instead use system
installed libbpf.
> libbpf-rs, libbpf-cargo: Support novendor feature

- libbpf-cargo/src/gen.rs
Prevent warnings in generated skeletons due to upper_case_acronyms or non_camel_case_types.
EG. The following enum will cause both warnings when compiling a generated skeleton (upper case is limited to clippy)
```
enum file_event_t {
CREATE,
CLOSE,
DELETE,
LINK,
};
```
> Prevent Rust Warnings

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/test.rs
impl Default for unions so that they can be placed inside of other aggregates
re-implement the test_btf_dump_definition_anon_enum as it was
accidentally overwritten in commit:
3e083dd
> impl Default for unions

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/test.rs
Before, forgot to check int encoding for bools. Rust bools appear to be
1 byte wide just like C bool.
This fixes #129.
> libbpf-cargo: btf: Support bool type

- libbpf-rs/src/program.rs
This PR adds a `attach_sk_lookup` in order to implement [sk_loopup programs](https://www.kernel.org/doc/html/latest/bpf/prog_sk_lookup.html).
> libbpf-rs: add sk_lookup

- Cargo.lock
- libbpf-cargo/Cargo.toml
- libbpf-rs/Cargo.toml
- libbpf-rs/src/perf_buffer.rs
Start using new perf_buffer__new() API variant that's going to be the
only one in libbpf 1.0.
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
> perf_buffer: switch to new libbpf v0.6 perf_buffer__new() API

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/test.rs
In libbpf 6.0+ bpf_printk is using a static const for the ____fmt
variable under certain conditions. This is causing an error when
generating rust code for the rodata.  libbpf-rs should skip generation
of fields for static variables.
Solution: Skip generation of static variables while parsing datasec
> libbpf-cargo: Skip the output of datasec static variables

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/metadata.rs
libbpf-cargo does not have a clean pass of 'cargo clippy'.
Solution: Implement changes recommended by running cargo clippy over
libbpf-cargo source files
NOTE: libbpf-rs has many more clippy recomendations.  I am not comfortable working on that until the unit tests are working as per PR: https://github.com/libbpf/libbpf-rs/pull/158
> libbpf-cargo: Implement cargo clippy recommendations

- .github/workflows/rust.yml
- examples/capable/src/main.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/object.rs
- libbpf-rs/src/skeleton.rs
This change enables a clean clippy check over the entire libbpf-rs project assuming clippy defaults (+branches_sharing_code linter).  IMHO clippy enhances the code quality of the project.
> Implement Clippy recommendations on examples and libbpf-rs

- libbpf-cargo/src/metadata.rs
- libbpf-cargo/src/test.rs
This allows having sections of the following form in Cargo.toml:
```
[package.metadata.deb]
```
Previously, they would give a hard error:
```
$ cargo libbpf make
Compiling BPF objects
Error: Failed to compile BPF objects
Caused by:
Failed to process package=bpf-graceful-restart, error=unknown variant `deb`, expected `libbpf`
```
Serde by default requires all enum variants to be known ahead of time;
this works by changing the deserialized type to a struct instead.
Signed-off-by: Joshua Nelson <jnelson@cloudflare.com>
Fixes https://github.com/libbpf/libbpf-rs/issues/164.
> Allow having package.metadata sections that aren't for libbpf

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/test.rs
An unnamed union in C cannot be generated to rust code as rust demands
names on it's variables.
Solution: Give the union a name of __unnamed_X where X is the
declaration of the union.
NOTE: The usage of __unnamed_ and __anon_ requires the consumer-programmer of the skeleton have intimate knowledge of the generated skeleton.   Please see the usage of __unnamed _anon_1 and __unnamed_anon_4 in the test code.  IMHO this is exceptionally confusing to the users of libbpf-cargo.
We need to figure out the best way to make this easier for consumers; but this code will at least stop compile breaking unnamed union code.
> libbpf-cargo: Cannot generate unnamed unions

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/test.rs
Rust can have a field name be the same as the type.  __unnamed_ is
not necessary for unnamed unions, and harms readability
> libbpf-cargo: __unnamed_ is unnecessary as a field prefix

- libbpf-cargo/src/build.rs
- libbpf-cargo/src/gen.rs
- libbpf-cargo/src/metadata.rs
Clang includes the name of the directory where includes are stored in the `.debug_line` section of
the headers when debug info is enabled. Since the directory was randomly created on each new run,
that meant the object file varied randomly each time it was created.
This changes the directory name to be consistently in a subdirectory of `target/` instead.
Fixes https://github.com/libbpf/libbpf-rs/issues/163. Closes https://github.com/libbpf/libbpf-rs/pull/169.
Signed-off-by: Joshua Nelson <jnelson@cloudflare.com>
> libbpf-cargo: Make generated object files deterministic by not using a temporary directory for include headers

- examples/query/src/main.rs
> libbpf-rs: Fix clippy error in examples/query

- .github/workflows/rust.yml
Without this action, we otherwise default to using the
ubuntu-latest version of Rust.
> build: Download latest version of Rust before building

- libbpf-cargo/src/gen.rs
- libbpf-rs/src/object.rs
`bpf_map__next` and `bpf_program__next` are deprecated in libbpf in favor of
`bpf_object__next_map` and `bpf_object__next_program`.
This patch replaces our uses of `bpf_map__next` and `bpf_program__next` with
the updated APIs.
> Replace deprecated libbpf functions

- libbpf-rs/src/link.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/perf_buffer.rs
- libbpf-rs/src/program.rs
- libbpf-rs/src/ringbuf.rs
- libbpf-rs/src/util.rs
This patch adds helper functions for parsing the return code into its
corresponding Result.
> util: Add parse_ret helper functions

- libbpf-rs/src/perf_buffer.rs
- libbpf-rs/src/util.rs
This patch adds epoll_fd, consume, consume_buffer, buffer_cnt, and
buffer_fd support for perf buffers.
This is part of a larger effort to reach feature-parity with libbpf.
> perf_buffer: Add epoll_fd, consume, consume_buffer, ... wrappers

- .github/workflows/rust.yml
Ubuntu 20.04 has recently added BTF into it's kernel
BTF tests can now be run
> libbpf-rs: Turn on tests for BTF

- libbpf-rs/src/object.rs
- libbpf-rs/src/print.rs
- libbpf-rs/src/program.rs
Add bpf_program__set_autoload / bpf_program__set_attach_target equivalent API to libbpf-rs.
Closes #175 and #176.
> libbpf-rs: Add set_autoload/set_attach_target to OpenProgram

- libbpf-rs/src/iter.rs
- libbpf-rs/src/link.rs
- libbpf-rs/src/query.rs
Let's follow the Rust ([0]) and libbpf ([1]) naming conventions,
omit the get_ prefix for getters.
[0]: https://github.com/rust-lang/rfcs/blob/master/text/0344-conventions-galore.md#gettersetter-apis
[1]: https://github.com/libbpf/libbpf/wiki/Libbpf:-the-road-to-v1.0
> libbpf-rs: Omit get_ prefix for getters

- libbpf-cargo/src/btf/btf.rs
Replace deprecated btf__get_raw_data with btf__raw_data.
> libbpf-cargo/btf: Replace deprecated btf__get_raw_data

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/btf/c_types.rs
- libbpf-cargo/src/btf/types.rs
Add support for BTF_KIND_FLOAT and BTF_KIND_DECL_TAG.
Closes #172.
> libbpf-cargo/btf: Add BTF_KIND_FLOAT and BTF_KIND_DECL_TAG

- libbpf-rs/src/program.rs
add wrapper around `bpf_program__insn_cnt`
Fixes #200
> add bpf_insn wrapper to read program instructions

- Cargo.lock
- libbpf-cargo/Cargo.toml
- libbpf-rs/Cargo.toml
- libbpf-rs/src/object.rs
- libbpf-rs/tests/test.rs
libbpf-sys 0.7.1 includes a newer libbpf version that has many useful features including the new
BPF_KPROBE_SYSCALL macro. Let's update so that users that are using a vendored libbpf can
take advantage of these features.
> libbpf-rs: update libbpf-sys dependency

- libbpf-rs/src/map.rs
Libbpf has support for BPF STRUCT_OPS
https://lwn.net/Articles/809092/ which allows for bpf to implement
specific kernel's function pointers.
libbpf has bpf_map__attach_struct_ops() to attach these. This commit
adds the equivalent functionality to libbpf-rs without which
STRUCT_OPS cannot be used.
> Add struct_ops attach support

- libbpf-rs/src/map.rs
PR 222 added attach_struct_ops but there were some requests for
changes from @insearchoflosttime after the PR was pulled. This commit
addresses the feedback.
Signed-off-by: Dan Schatzberg <schatzberg.dan@gmail.com>
> libbpf-rs: Fix attach_struct_ops

- examples/capable/build.rs
- examples/runqslower/build.rs
- examples/tc_port_whitelist/build.rs
- libbpf-cargo/src/lib.rs
- libbpf-cargo/src/test.rs
It might be desirable for an end-user to run SkeletonBuilder directly on an object file
rather than compiling with clang. This could be useful for a few reasons, such as
establishing greater control over the build process or working with vendored object files.
As such, this commit refactors SkeletonBuilder slightly, breaking generate() up into
build() and generate() respectively. A new function is added called build_and_generate()
which encompasses the old behaviour. To make this work, we also remove the source argument
from SkeletonBuilder::new() and instead shift over to SkeletonBuilder::source() and
SkeletonBuilder::obj() to specify a source and object file respectively.
In cases where SkeletonBuilder::obj is missing, we fall back to creating a temporary
directory as before.
Note that …
> libbpf-cargo: enable split building and generation in SkeletonBuilder

- Cargo.lock
- examples/bpf_query/Cargo.toml
- examples/bpf_query/src/main.rs
- examples/capable/Cargo.toml
- examples/capable/src/main.rs
- examples/runqslower/Cargo.toml
- examples/runqslower/src/main.rs
- examples/tc_port_whitelist/Cargo.toml
- examples/tc_port_whitelist/src/main.rs
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/main.rs
As stated in the [docs](https://github.com/TeXitoi/structopt/blob/master/README.md#maintenance): structopt is now in maintenance mode.
This PR migrates to use the new [clap derive](https://github.com/clap-rs/clap/tree/master/clap_derive) functionality that has an almost identical interface.
I have updated and compiled all of the examples to ensure they are still working as expected.
Signed-off-by: Dan Bond <danbond@protonmail.com>
> libbpf-cargo: use clap derive

- Cargo.lock
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/btf/types.rs
- libbpf-rs/Cargo.toml
- libbpf-rs/src/program.rs
* Update libbpf-sys to v0.8.0
* Replace deprecated libbpf APIs
* Add Btf::get_kind for libbpf-cargo
* Add support for BTF_KIND_TYPE_TAG
> Minor updates for libbpf-rs

- libbpf-cargo/src/gen.rs
- libbpf-rs/src/object.rs
SkelBuilder only has the open method, and we can't easily pass in parameters like btf_custom_path.
Therefore, this commit adds the open_opts method for SkelBuilder. Developers can obtain an instance of libbpf_sys::bpf_object_open_opts through obj_builder.opts(std::ptr::null()), and then set the btf_custom_path parameter.
Signed-off-by: Shuyi Cheng <chengshuyi@linux.alibaba.com>
> libbpf-cargo: Add open_opts method for SkelBuilder.

- .github/workflows/rust.yml
- Cargo.lock
- examples/capable/Cargo.toml
- libbpf-cargo/Cargo.toml
- libbpf-rs/Cargo.toml
To statically link elfutils and libz. Tested on [rbperf](https://github.com/javierhonduco/rbperf) compiled with `RUSTFLAGS="-L /usr/lib -L /usr/lib64" cargo b`
**With the feature disabled (the default)**
```
[javierhonduco@fedora rbperf]$ ldd target/debug/rbperf
linux-vdso.so.1 (0x00007fffa8de3000)
libelf.so.1 => /lib/libelf.so.1 (0x00007ff9a5727000)
libz.so.1 => /lib64/libz.so.1 (0x00007ff9a570d000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff9a56ed000)
libm.so.6 => /lib64/libm.so.6 (0x00007ff9a560f000)
libc.so.6 => /lib64/libc.so.6 (0x00007ff9a540e000)
/lib64/ld-linux-x86-64.so.2 (0x00007ff9a5fa2000)
```
**With the static feature**
```
[javierhonduco@fedora rbperf]$ ldd target/debug/rbperf
linux-vdso.so.1 (0x00007ffc5ed6a000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 …
```
> Expose libbpf-sys' static feature

- libbpf-rs/src/map.rs
This PR exposes libbpf's `set_type`, `set_key_size`, and `
set_value_size`.
The reason why this can be useful is, for example, while migrating an
application that uses perf buffers to ring buffers, while maintaining
backwards compatibility for systems that don't have BPF ring buffers
yet.
In this program, only one map called events is created, and before
loading the program and creating the maps, we modify its type, as well
as other parameters.
```rust
let mut maps = open_skel.maps_mut();
let events = maps.events();
if options.use_ringbuf {
events.set_type(MapType::RingBuf).unwrap();
events.set_key_size(0).unwrap();
events.set_value_size(0).unwrap();
events.set_max_entries(1024).unwrap();
} else {
events.set_type(MapType::PerfEventArray).unwrap();
events.set_key_size(4).unwrap(); …
```
> map: Implement more open map setters

- Cargo.lock
- libbpf-cargo/Cargo.toml
As described in
https://github.com/libbpf/libbpf-rs/security/dependabot/1, there are DoS
vulnerabilities associated with regex version 1.5
This commit updates the regex version to 1.6.0
> libbpf-cargo: update regex to 0.16.0 to mitigate DoS vulnerabilities

- libbpf-rs/src/map.rs
As part of the initiative to reach feature-parity with libbpf-1.0, this
commit adds:
* set_map_flags
* set_numa_node
* set_map_extra
* set_autocreate
* set_pin_path
> libbpf-rs: Add more setter functionalities on open maps

- Cargo.lock
- libbpf-rs/src/object.rs
bpf_map__def() is deprecated since libbpf-0.8.
This commit changes the code to use the appropriate getters/setters
instead.
> libbpf-rs: remove deprecated bpf_map__def() usage

- libbpf-rs/src/tc.rs
Existing docs were inconsistent with other API docs. Mainly added:
* Terser summary level doc
* Fix broken links / formatting
* Phrasing
> Fix up TcHook docs

- libbpf-rs/src/map.rs
Map's fd is already defined as i32. We do not need to cast it
explicitly with "fd as i32".
> libbpf-rs: clean up unnecessary 'fd as i32' casting in maps

- libbpf-rs/src/ringbuf.rs
As part of the initiative to reach feature-parity with libbpf-1.0, this
commit adds a wrapper for the ringbuffer__epoll_fd API.
> libbpf-rs: Add wrapper for ringbuffer__epoll_fd

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/btf/types.rs
- libbpf-cargo/src/gen.rs
- libbpf-cargo/src/test.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/ringbuf.rs
These include warnings such as:
warning: you are deriving `PartialEq` and can implement `Eq`
--> libbpf-rs/src/map.rs:576:50
|
576 | #[derive(Clone, TryFromPrimitive, IntoPrimitive, PartialEq,
Display)]
|                                                  ^^^^^^^^^ help:
consider deriving `Eq` as well: `PartialEq, Eq`
|
= note: `#[warn(clippy::derive_partial_eq_without_eq)]` on by
default
= help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
warning: very complex type used. Consider factoring parts into `type`
definitions
--> libbpf-rs/src/ringbuf.rs:11:9
|
11 |     cb: Box<dyn FnMut(&[u8]) -> i32 + 'a>,
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(clippy::type_complexity)]` on by default
= help: for …
> Fix cargo clippy warnings

- libbpf-rs/src/iter.rs
- libbpf-rs/src/lib.rs
- libbpf-rs/src/link.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/object.rs
- libbpf-rs/src/perf_buffer.rs
- libbpf-rs/src/program.rs
- libbpf-rs/src/query.rs
- libbpf-rs/src/ringbuf.rs
- libbpf-rs/src/skeleton.rs
This is a simple quality-of-life improvement to make it a bit easier to use and discover the library.
```
fn main() {
for prog in libbpf_rs::query::ProgInfoIter::default() {
println!("{:#?}", prog);
}
for prog in libbpf_rs::query::LinkInfoIter::default() {
println!("{:#?}", prog);
}
for prog in libbpf_rs::query::MapInfoIter::default() {
println!("{:#?}", prog);
}
}
```
> libbpf-rs: Add derive(Debug) to query-related structs and enums

- .github/workflows/rust.yml
- README.md
Version 1.58 is the minimum version that supports using captured identifiers in format strings, which is used within the libbpf-rs codebase.
This patch upgrades the minimum Rust version from 1.56 to 1.58.
> Update minimum supported Rust version from 1.56 to 1.58

- Cargo.lock
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/gen.rs
- libbpf-rs/Cargo.toml
- libbpf-rs/src/object.rs
v1!
libbpf-sys release tag: [v1.0.0](https://github.com/libbpf/libbpf-sys/releases/tag/1.0.0%2Bv1.0.0)
Outside of updating the dependency, other changes:
* libbpf-rs: Remove use of deprecated bpf_object_open_opts fields [0]
* libbpf-cargo: Remove use of deprecated bpf_map__def call [1]
[0] https://github.com/libbpf/libbpf/commit/d8454ba8ad83514a5afc6e3d05bddb61f299d5f4#diff-ecec02d2345e3666818b41e879a7e9242acbd0575f20f796b2d8b7fe0cf2841bL127
[1] https://github.com/libbpf/libbpf/commit/d8454ba8ad83514a5afc6e3d05bddb61f299d5f4#diff-ac82747bd450e8e5e0805a99d6c24afa9fcbfcddffbce5aa3288b2edabe17419L9776
Signed-off-by: Milan Landaverde <milan@mdaverde.com>
> Update to libbpf-sys v1.0.0

- .github/workflows/rust.yml
GitHub is complaining about usage of old Node.js on every GitHub Actions run:
> Node.js 12 actions are deprecated. For more information see:
> https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> Please update the following actions to use Node.js 16: actions/checkout,
> actions-rs/toolchain, actions/checkout
Update the actions in question to get rid of those warnings.
> Update checkout and toolchain actions

- .github/workflows/rust.yml
Over in https://github.com/libbpf/libbpf-rs/pull/279 we fixed a regression caused by leakage of certain BPF objects. With this change we try to prevent such regressions from creeping in by enabling leak sanitizer when running our test suite in CI. Note that because we rely on unstable flags for said enablement, we need to run the nightly toolchain.
> Run leak sanitizer in CI

- libbpf-cargo/src/test.rs
The clippy will show error when checking:
error: deref which would be done by auto-deref
--> libbpf-cargo/src/test.rs:1036:32
|
1036 |     let btf = Btf::new("prog", &*mmap)
|                                ^^^^^^ help: try this: `&mmap`
|
= note: `-D clippy::explicit-auto-deref` implied by `-D warnings`
see the CI in #285.
> libbpf-cargo:  fix cargo clippy warnings in test

- README.md
It seems that the `libbpf-cargo` version 0.13 and `libbpf-rs` version 0.19 has been release.
While I used the origin version 0.12 and 0.18, some error occured:
```
error: failed to select a version for `libbpf-sys`.
... required by package `libbpf-rs v0.18.0`
... which satisfies dependency `libbpf-rs = "^0.18"` of package `runqslower v0.1.0 (/home/yunwei/eunomia-bpf/libbpf-rs/examples/runqslower)`
versions that meet the requirements `^0.8.0` are: 0.8.3+v0.8.1, 0.8.2+v0.8.1, 0.8.1+v0.8.0, 0.8.0+v0.8.0
the package `libbpf-sys` links to the native library `libbpf`, but it conflicts with a previous package which links to `libbpf` as well:
package `libbpf-sys v1.0.4+v1.0.1`
... which satisfies dependency `libbpf-sys = "^1.0.3"` of package `libbpf-cargo v0.13.1 …
```
> Update the dependencies version for README.md

- .github/workflows/rust.yml
- libbpf-cargo/Cargo.toml
- libbpf-rs/Cargo.toml
Compilation problems caused by unsupported Rust features due to an old toolchain can be confusing. They also make it non-obvious what the minimum Rust version to upgrade to is.
Starting with Rust 1.56, Cargo honors the rust-version field [0] that causes it to fail compilation with a meaningful error message if the toolchain is not recent enough.
Set it for libbpf-rs and libbpf-cargo to have nicer errors reported to users in case of old toolchain usage.
[0] https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
> Enforce minimum Rust version from Cargo

- libbpf-rs/src/ringbuf.rs
- libbpf-rs/src/tc.rs
In instances where err is already a 32-bit int, 'err as i32' is an unnecessary cast.
> Remove unnecessary 'err as i32' casts

- libbpf-cargo/src/test.rs
The libbpf-rs path detection in tests is broken. It's only working when run from the libbpf-cargo/ sub-directory, otherwise (including when run from the project root!) we get non-descriptive failures at runtime:
> ---- test::test_skeleton_datasec stdout ----
> Metadata for package=proj
>         null
> Found bpf progs to compile:
>         UnprocessedObj { package: "proj", path: "/tmp/.tmpnoGGx9/proj/src/bpf/prog.bpf.c", out: "/tmp/.tmpnoGGx9/proj/target/bpf", name: "prog" }
> Building /tmp/.tmpnoGGx9/proj/src/bpf/prog.bpf.c
> Metadata for package=proj
>         null
> Found bpf objs to gen skel:
>         UnprocessedObj { package: "proj", path: "/tmp/.tmpnoGGx9/proj/src/bpf/prog.bpf.c", out: "/tmp/.tmpnoGGx9/proj/target/bpf", name: "prog" }
> thread 'test::test_skeleton_datasec' panicked …
> Fix libbpf-rs path detection in tests

- .github/workflows/rust.yml
- libbpf-rs/tests/test.rs
CI should really run on all pushes, or it is super cumbersome to test change quickly. Adjust the workflow accordingly.
> Run CI on push events

- libbpf-cargo/src/test.rs
We have the assert_definition() helper for comparing actual output to expected output, panicking if the two don't match. The function takes care of printing the actual and expected output in nicely formatted form to stdout before performing the equality check (and, thus, irrespective of its outcome).
Currently, if the equality comparison done via assert_eq! macro fails we end up printing the expected and actual output *again*, but this time without formatting it properly (no interpretation of newline characters, for example).
Stop using assert_eq! in favor of assert!, which will only indicate the check that caused a panic (on assertion failure), but does not print actual and expected output, resulting in less confusing data on test failure.
> Stop using assert_eq! in assert_definition() helper function

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/test.rs
When a C struct is defined with greater-than-natural alignment (by tagging it with the respective attribute), our emitted Rust types end up being incorrect and not necessarily matching kernel types. The problem is that while we support adding padding between members as necessary, we do not make sure to pad to the BTF defined type size (which is how alignment is conveyed via BTF).
Let's ensure we pad up to this size, to ensure better (well, hopefully perfect...) match up between generated types and kernel definitions.
Fixes: #270
> Add necessary padding to overall struct type size

- libbpf-rs/src/query.rs
This makes it easier to use these structs in other data structures.
> Add derive(Clone) to the structs in query.rs.

- Cargo.lock
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/gen.rs
- libbpf-rs/Cargo.toml
- libbpf-rs/src/map.rs
- libbpf-rs/src/object.rs
- libbpf-rs/src/perf_buffer.rs
- libbpf-rs/src/program.rs
- libbpf-rs/src/ringbuf.rs
- libbpf-rs/src/skeleton.rs
- libbpf-rs/src/tc.rs
- libbpf-rs/tests/test.rs
Changes which fixed libbpf-sys compile breakage for 1.1.0 now cause breaks against 1.1.1.
These two commits fix those issues.
> Revert Changes to compile against libbpf-sys 1.1.0, update to 1.1.1

- libbpf-rs/src/link.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/object.rs
- libbpf-rs/src/perf_buffer.rs
- libbpf-rs/src/program.rs
- libbpf-rs/src/ringbuf.rs
- libbpf-rs/src/skeleton.rs
It is generally considered good practice to implement Debug on all public types of a crate [[0]][0] [[1]][1], in order to facilitate easier debugging by users.
Let's do just that for our remaining types that don't do it yet.
[0] https://rust-lang.github.io/api-guidelines/debuggability.html [1] https://rust-lang.github.io/api-guidelines/checklist.html
Closes: #260
> Provide Debug impl for remaining public types

- .github/workflows/rust.yml
Please see individual commits for descriptions, but as per my brief testing we:
> seem to be reducing total CI duration from somewhere between 7:20 minutes [0] and 9:30 minutes [1] down to about five minutes [2] while also reporting formatting and similar problems much earlier than beforehand.
[0] https://github.com/danielocfb/libbpf-rs/actions/runs/3913755036
[1] https://github.com/danielocfb/libbpf-rs/actions/runs/3906846913
[2] https://github.com/danielocfb/libbpf-rs/actions/runs/3915159222
> Split CI into more independently running jobs

- examples/bpf_query/Cargo.toml
- examples/runqslower/Cargo.toml
- examples/tproxy/Cargo.toml
It's not good style for us to have example code lying around without a license, to the point that it renders the example code completely useless, because it is unlikely to be safely reusable. This change proposes to license `bpf_query`, `runqslower`, and `tproxy` examples under `LGPL-2.1 OR BSD-2-Clause`, similar to the main library.
> Add license information bpf_query, runqslower, and tproxy examples

- libbpf-rs/src/perf_buffer.rs
- libbpf-rs/src/ringbuf.rs
As per https://github.com/libbpf/libbpf-rs/issues/224#issuecomment-1119996446 ring buffers and perf buffers can be polled from any thread. Hence, it is safe for us to implement `Send` for the corresponding Rust types, `RingBuffer` and `PerfBuffer`.
Closes: #224
> libbpf-rs: Implement `Send` for `PerfBuffer` and `RingBuffer`

- Cargo.lock
- libbpf-rs/Cargo.toml
- libbpf-rs/src/lib.rs
- libbpf-rs/src/linker.rs
- libbpf-rs/tests/test.rs
A while back libbpf got support for linking multiple BPF object files statically into a single one [0]. This functionality is useful in and off itself and should be exposed as such by this library, but it is also a suitable building block for ensuring deterministic skeleton creation [1] [2] [3].
As such, this change hooks it up. We mirror the libbpf APIs very closely, just packaging them up in a nicer Rust interface.
[0] https://lwn.net/ml/bpf/20210310040431.916483-6-andrii@kernel.org/ [1] https://github.com/libbpf/libbpf-rs/issues/177 [2] https://github.com/libbpf/libbpf-rs/issues/163 [3] https://github.com/libbpf/libbpf-rs/pull/169
> libbpf-rs: Add BPF linker support

- examples/tc_port_whitelist/Cargo.toml
It's not good style for us to have example code lying around without a license, to the point that it renders the example code completely useless, because it is unlikely to be safely reusable. This change proposes to license tc_port_whitelist example under LGPL-2.1 OR BSD-2-Clause, similar to the main library.
> Add license information tc_port_whitelist example

- .github/workflows/rust.yml
Just stumbled over the Swatinem/rust-cache action which seems to be a low-key way for caching dependencies once built. As per my brief testing here [0] [1] the relevant runtime of the two jobs affected decrease from ~4:30 min down to ~3:30, if not better. Let's give it a try.
[0] https://github.com/danielocfb/libbpf-rs/actions/runs/3970473231 [1] https://github.com/danielocfb/libbpf-rs/actions/runs/3970565645
> Enable dependency caching in CI

- .github/dependabot.yml
Now that we have decoupled our minimum supported Rust version checks from `Cargo.lock` [0], we can easily keep dependency versions up-to-date. Doing so will make sure that we always release with the most recent dependencies, which may include bug and security fixes. It will also help with enabling cargo audit/deny [2], depending on what we audit.
This change enables Dependabot for doing so. It will scan for updated packages and open pull requests. I've tried it out on my fork [1] and it worked fine.
[0] https://github.com/libbpf/libbpf-rs/pull/318
[1] https://github.com/danielocfb/libbpf-rs/pull/2 [2] https://github.com/libbpf/libbpf-rs/issues/187
> Enabled Dependabot for automatically updating locked versions of dependencies

- .github/workflows/rust.yml
- Cargo.lock
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/build.rs
- libbpf-cargo/src/gen.rs
- libbpf-cargo/src/test.rs
Clang generated BPF object files may contain DWARF information that
references paths to temporary directories, for example. That ends up
rendering our generated skeleton unstable, as it potentially changes
between invocations [0]. That can be unfortunate if the skeleton is
meant to be checked into version control.
Andrii suggested [1] stripping said DWARF information by linking the
object file, which strips it as a side effect. This change does so.
[0] https://github.com/libbpf/libbpf-rs/issues/163
[1] https://github.com/libbpf/libbpf-rs/pull/169#issuecomment-1006074629
Closes: https://github.com/libbpf/libbpf-rs/issues/177
> libbpf-cargo: Strip DWARF information from generated object files

- examples/capable/Cargo.toml
It's not good style for us to have example code lying around without a license, to the point that it renders the example code completely useless, because it is unlikely to be safely reusable. This change proposes to license capable example under LGPL-2.1 OR BSD-2-Clause, similar to the main library.
> Add license information to capable example

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/test.rs
Rust version 1.62 made it possible to use #[derive(Default)] (see: https://github.com/rust-lang/rust/pull/94457)
As of rust version 1.68, the default clippy configuration will print a warning for manually impl Derive on enums. As such, users of libbpf-cargo will begin to experience clippy warnings when they migrate to version 1.68.
libbpf-cargo's minimum rust version is 1.58, thus the recommended method to remove the clippy warnings, is not yet an option for the project.
Add a #[allow(clippy::derivable_impls)], to suppress the clippy warning on all generated skeletons.
Add a TODO to remove this once the project moves to a minimum rust version of 1.62
> Ignore clippy lint warning for derive default

- examples/capable/build.rs
- examples/capable/src/main.rs
- examples/runqslower/build.rs
- examples/runqslower/src/main.rs
- examples/tc_port_whitelist/build.rs
- examples/tc_port_whitelist/src/main.rs
- examples/tproxy/build.rs
- examples/tproxy/src/bin/proxy.rs
- examples/tproxy/src/main.rs
- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/build.rs
- libbpf-cargo/src/gen.rs
- libbpf-cargo/src/lib.rs
- libbpf-cargo/src/make.rs
- libbpf-cargo/src/test.rs
- libbpf-rs/src/linker.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/object.rs
- libbpf-rs/src/print.rs
- libbpf-rs/src/skeleton.rs
- libbpf-rs/tests/test.rs
This patch changes a few nuisances from recent pull requests:
- Rename `Linker::add()` to `add_file` to follow libbpf naming more
closely (I still kept `Linker::link()` (as opposed to finalize)) as it
seems apt.
- Fix `SEC` used in `test_skeleton_builder_deterministic`. The program
would no longer load with libbpf 1.0.
- Use `vmlinux.h` instead of `<linux/bpf.h>` for consistency with other
skeletons.
> libbpf-rs: Few changes to recent patches

- .github/workflows/audit.yml
- deny.toml
This change enables cargo-deny to run every week to check for advisories and license violations, among other things. Doing so will make us aware of problems potential problems in a timely fashion and give users peace of mind [0].
[0] https://github.com/libbpf/libbpf-rs/issues/187#issuecomment-1046076331
Closes: #187
> Run cargo-deny weekly

- .github/workflows/rust.yml
If we bump dependencies manually in `Cargo.toml` we may end up forgetting about adjusting `Cargo.lock` in the process, depending on how we go about it. That's not great for users as it will cause spurious changes when they build a checkout.
Luckily for us, it's an easy thing to detect: we should build with `--locked`, which will cause the build process to fail if the two files do not agree. Use it in our CI workflow accordingly.
> Build with --locked in CI

- Cargo.lock
We had a conflict between https://github.com/libbpf/libbpf-rs/pull/344 and https://github.com/libbpf/libbpf-rs/pull/346 that resulted in an outdated Cargo.lock. Fix it up.
> Fix "merge conflict" between two recent dependency updates

- Cargo.lock
- libbpf-rs/Cargo.toml
This change bumps the strum_macros dependency we consume from 0.23 to 0.24. Not only does that get us up-to-date with recent developments, it will also eliminate one copy of `heck` being pulled in.
> Bump strum_macros from version 0.23 to 0.24

- Cargo.lock
- examples/bpf_query/Cargo.toml
- examples/tc_port_whitelist/Cargo.toml
- examples/tproxy/Cargo.toml
- libbpf-rs/Cargo.toml
Some of our examples use nix in version `0.25` while others use `0.26`. That's detrimental to compile time and potentially binary size (though not really that relevant here, because it's only examples we are talking about).
Switch to using version `0.26` everywhere.
> Bump nix from version 0.25 to 0.26

- libbpf-cargo/src/lib.rs
- libbpf-rs/src/lib.rs
- libbpf-rs/src/perf_buffer.rs
- libbpf-rs/src/ringbuf.rs
We have a few implicitly `unsafe` operations in `unsafe` functions. Currently these don't require explicit wrapping in `unsafe {}`. That has arguably been identified as a wrong design decision of Rust, but it may only be changed in a new edition (if at all), because it would be a breaking change.
The `unsafe_block_in_unsafe_fn` lint [0] has been devised to fix this behavior, but it has to explicitly be opted in (though it may become the default eventually). Let's deny it, forcing us to make all `unsafe` blocks explicit.
[0] https://github.com/rust-lang/rfcs/blob/master/text/2585-unsafe-block-in-unsafe-fn.md
> Make unsafe blocks explicit

- examples/bpf_query/LICENSE.LGPL-2.1
- examples/capable/LICENSE.LGPL-2.1
- examples/runqslower/LICENSE.LGPL-2.1
- examples/tc_port_whitelist/LICENSE.LGPL-2.1
- examples/tproxy/LICENSE.LGPL-2.1
The previous PR initially used the wrong filenames when linking the LGPL license texts into the example crates, and when fixing them I only renamed the symlinks and not what they point to.
Signed-off-by: Michel Alexandre Salim <salimma@fedoraproject.org>
> Properly fix license symlinks

- libbpf-rs/src/link.rs
`Program` is a re-usable object and must not be consumed while updating the `link`.
Follow-up for #369
When an eBPF program is loaded and attached by a custom loader based on `libbpf-rs`, one or more `Link` objects are created and pinned to bpffs. Once the loader is restarted to attach another program, it needs to load existing `Link` pins and call `update_prog()` method.
Since a single eBPF program can be assigned to more than one hook and since dropping of `Program` may invoke its unloading, the `update_prog()` must not consume the `Program` instance, but must use it as a mut reference. Just Like the underlying `libbpf-sys` function.
> link: pass program as mut reference to update_prog

- libbpf-rs/src/map.rs
- libbpf-rs/tests/test.rs
Map updates in various shapes and forms are just system call wrappers and the kernel ensures safety in the context of multiple concurrent updates. As such, it makes sense for us to reflect that in the signatures of the corresponding methods by allowing for a &self receiver. Requiring a mutable reference there leads to awkward usage patterns in certain scenarios.
> Allow various Map system call wrappers to work on shared references

- .github/workflows/publish.yml
A while back we added the publish workflow for publishing new releases of the workspace's crates to crates.io. This change enhances this workflow with the following logic:
1) we check that both the libbpf-rs and libbpf-cargo version are the
same; we have decided to bump both in unison as that simplifies our
lives
2) once we successfully published new versions of said crates, we create
a git tag along with a GitHub release
References: #281
> Enhance publish workflow

- libbpf-rs/src/object.rs
- libbpf-rs/src/skeleton.rs
According to the [documentation](https://doc.rust-lang.org/alloc/boxed/index.html#considerations-for-unsafe-code), any use of aliases of a box, be it raw pointers or references, is invalid after the box has been moved/mutated/borrowed, thus the box aliasing that was happening here was Undefined Behaviour. Since the only reason the box was kept was so that it would be dropped in the destructor, I removed it from the fields of the struct and then dropped it manually in the destructor.
I also added the one missing NonNull check. This will guarantee that bugs in the generated code fail faster since uninitialized pointers will be detected sooner from a panic instead of a seg-fault
> Remove undefined behavior from ObjectSkeletonConfig.

- README.md
- libbpf-cargo/Cargo.toml
libbpf-cargo fails to publish because of:
> error: all dependencies must have a version specified when publishing.
> dependency `libbpf-rs` does not specify a version
> Note: The published dependency will use the version from crates.io,
> the `path` specification will be removed from the dependency declaration.
Hence, explicitly specify the version to use. Also bump the recommended versions to use in the README.
> Specify libbpf-rs version in libbpf-cargo/Cargo.toml

- .github/workflows/publish.yml
Currently publishing multiple crates in a workspace is not an atomic operation. That will hopefully change eventually on the Cargo side, but currently it means that we may end up publishing one crate version and then failing to publish the other in our workflow. To minimize the chances of that happening, let's include a cargo package run, which does some basic sanity checking, before evening attempting to publish.
> Check package creation as part of publish workflow

- CONTRIBUTING.md
- libbpf-rs/CHANGELOG.md
Introduce a CHANGELOG for keeping track of changes. Right now, we intend to have separate logs for the two crates (only one for libbpf-rs is created as part of this change, because only it has changes over the last release). The format is mostly free-form and expected to evolve over time. The contents will eventually appear in the corresponding GitHub release.
Closes: #281
> Add CHANGELOG for keeping track of changes

- .github/workflows/test.yml
I forgot to include that earlier, but with commit bf09e444d410 ("Use single line use statements") we include rustfmt configuration options that are only used on nightly.
With this change we adjust CI to use a nightly toolchain so that we can actually enforce the new style.
> Use nightly rustfmt in CI

- libbpf-cargo/CHANGELOG.md
- libbpf-rs/CHANGELOG.md
I went back over the notable changes made to libbpf-rs and libbpf-cargo and populated our CHANGELOG files accordingly.
> Fill in notable changes made for 0.20.0

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/program.rs
As part of the initiative to reach feature-parity with libbpf-1.0, this commit adds wrapper functions around:
* bpf_program__set_log_level
* bpf_program__autoload
* bpf_program__log_level
This is change is a continuation of https://github.com/libbpf/libbpf-rs/pull/251.
> libbpf-rs: Add autoload and log level APIs for programs

- libbpf-cargo/src/btf/btf.rs
- libbpf-cargo/src/test.rs
Now that we have bumped our minimum supported Rust version, we can revert commit 5553d9ce572e ("Ignore clippy lint warning for derive default") and tag default variants with `#[default]` instead.
> Remove explicit allowance of derive default clippy lint warning

- Cargo.lock
- examples/capable/Cargo.toml
- libbpf-rs/Cargo.toml
Now that we use `1.63` as the minimum supported Rust version, we can bump `phf` up to `0.11`. In so doing we eliminate a few transitive dependencies while getting the newest and greatest.
> Update phf dependency to 0.11

- .github/PULL_REQUEST_TEMPLATE.md
This change instantiates a pull request template that ensures that contributors are aware of the Contributor's Guide, which lays out basic requirements that each pull request should adhere by.
> Introduce pull request template

- .github/workflows/test.yml
- libbpf-rs/src/btf/mod.rs
See https://github.com/d-e-s-o/libbpf-rs/actions/runs/4602666687/jobs/8131885274 for failure.
> Fix pointer mismatch causing build failure on `aarch64`

- libbpf-cargo/src/gen/btf.rs
- libbpf-rs/src/btf/mod.rs
- libbpf-rs/src/link.rs
This change removes the `Link::get_fd()` method, which has been deprecated for several releases by now.
> Remove deprecated `Link::get_fd()` method

- .github/workflows/publish.yml
Running cargo --no-verify in the root of the workspace checks packaging of all workspace members, including the examples.
We do not currently (and have no intention to) publish the examples, however. As such, let's verify only the members that we intend to publish. Also make use of Cargo's --package argument for the package and publish sub-commands we use, as that minimizes hard coded paths.
> Verify packages in workspace member directories

- .github/workflows/test.yml
- libbpf-rs/src/btf/mod.rs
CI and the clippy step specifically choke on the `bpf_query` example with Rust `1.69`, because of some false positive warning that we cannot disable.
Work with `1.68.2` for the time being.
> Run clippy on 1.68.2

- CONTRIBUTING.md
We require all commits in a pull request (and the broader repository history in general) to represent a compilable and testable (i.e., all tests passing successfully) snapshot of all components in the repository.
Make that explicit in the CONTRIBUTING guide.
> Adjust CONTRIBUTING to mention building commits

- libbpf-rs/CHANGELOG.md
- libbpf-rs/Cargo.toml
- libbpf-rs/src/error.rs
An error such as "errno: 1" doesn't tell users particularly much. Provide more information by stringifying `errno` using `strerror_r` and including this information in the textual representation of the `Error::System` variant.
> Include textual errno representation in Error::System Display impl

- libbpf-rs/src/map.rs
Fix `Map::create()` to use `util::parse()` instead of directly evaluating the return code and getting it wrong by not negating.
> Use util::parse() in Map::create constructor

- .github/workflows/test.yml
- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/program.rs
- libbpf-rs/src/util.rs
- libbpf-rs/tests/test.rs
This change fixes the `sz` member initialization of `bpf_uprobe_opts` objects that we use in the uprobe attach code. The previously incorrect size could lead to libbpf failing the attachment on optimized builds, where the size of Program objects was different to dev ones.
Fixes: #447
> Properly zero initialize uprobe opts `sz` member

- .github/dependabot.yml
It is easier to manage small batches of dependency updates than it is for large once. Run Dependabot daily instead of weekly to get closer to this ideal.
> Run Dependabot daily

- examples/tc_port_whitelist/src/main.rs
- examples/tproxy/src/main.rs
- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/iter.rs
- libbpf-rs/src/link.rs
- libbpf-rs/src/program.rs
- libbpf-rs/tests/test.rs
- libbpf-rs/tests/test_tc.rs
In recent times we started using file descriptor abstractions over "raw" integers. As part of that we also relied on the `AsFd` trait and provided implementations for the same.
Given that we implement this trait, it no longer makes sense to have a dedicated `fd()` method. With this change we remove it from the `Program` type.
> Remove Program::fd() method

- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/lib.rs
- libbpf-cargo/src/test.rs
- libbpf-rs/src/btf/types.rs
- libbpf-rs/src/lib.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/object.rs
- libbpf-rs/src/perf_buffer.rs
- libbpf-rs/src/program.rs
- libbpf-rs/src/ringbuf.rs
- libbpf-rs/src/skeleton.rs
It's arguably confusing to see a definition such as
```rust
impl<'a> OpenTproxySkel<'a> {
pub fn maps(&self) -> OpenTproxyMaps {
OpenTproxyMaps { inner: &self.obj }
}
}
```
because it omits the fact that the `OpenTproxyMaps` type actually has a lifetime associated with it.
Let's make sure to make lifetimes explicit to prevent such confusion from the start.
> Stop eliding lifetimes

- Cargo.lock
The `proc-macro2` crate is failing to build on nightly, caused redness all over the place. Bump its version to make the issue go away.
> Bump proc-macro2 dependency

- .github/workflows/publish.yml
We can't really verify the `libbpf-cargo` package because it unconditionally attempts to pull `libbpf-rs` from `crates.io`, where it can't find the specified version because it has not yet been published. For the time being, make do without checking `libbpf-cargo`.
> Don't dry-run package libbpf-cargo as part of publish workflow

- Cargo.lock
libbpf-sys 1.2.0 has just been yanked. Let's update to 1.2.1.
> Update libbpf-sys to 1.2.1

- libbpf-cargo/src/test.rs
When assert_definition() fails we currently end up reporting the very assert!() invocation as failure location. That's not exactly useful. Annotate the function with #[track_caller] to make sure that we see the call site instead.
Before:
> thread 'test::test_btf_dump_definition_struct_inner_anon_union' panicked at 'assertion failed: eo == ao', libbpf-cargo/src/test.rs:1139:5
(that's
https://github.com/libbpf/libbpf-rs/blob/fb30a431a878a7d5da8e33091d6eb4e837577dba/libbpf-cargo/src/test.rs#L1139)
Now:
> thread 'test::test_btf_dump_definition_struct_inner_anon_union' panicked at 'assertion failed: eo == ao', libbpf-cargo/src/test.rs:1932:5
(that's
https://github.com/libbpf/libbpf-rs/blob/fb30a431a878a7d5da8e33091d6eb4e837577dba/libbpf-cargo/src/test.rs#L1931)
> Annotate `assert_definition()` helper with `#[track_caller]`

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
It arguably makes very little sense for all "regular" fields in libbpf-cargo generated types to be publicly accessible, while padding fields are not.
Mark them as public as well. That's similar to what cbindgen does, with its named padding members.
Closes: #421
> Make padding fields of generated types `pub`

- .github/workflows/test.yml
- Cargo.lock
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/Cargo.toml
- libbpf-cargo/README.md
- libbpf-rs/CHANGELOG.md
- libbpf-rs/Cargo.toml
- libbpf-rs/README.md
- libbpf-rs/src/map.rs
Update the bitflags dependency to 2.0. Some changes to this new major version were breaking our code and required adjustments. See https://github.com/bitflags/bitflags/releases/tag/2.0.0 for relevant details.
> Bump bitflags to 2.0

- examples/tc_port_whitelist/src/main.rs
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/lib.rs
- libbpf-cargo/src/main.rs
- libbpf-cargo/src/metadata.rs
There are a bunch of occasions where we wrongly embed errors into a string and report the resulting string as a new error. Fix them by creating proper error chains.
> Improve error context chaining

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
Rust does not implement `Default` for pointers, no matter if the pointee implements the trait. As such, a bunch of our generated code does not compile. Specifically, bindings for struct types with a `Default` auto-derive and which contain pointers do not compile. Adjust the generation logic to emit a `Default` impl when a struct contains a pointer.
> Implement Default for struct containing pointers

- Cargo.lock
- libbpf-rs/CHANGELOG.md
- libbpf-rs/Cargo.toml
- libbpf-rs/src/map.rs
This change reverts commit 7134192d21747dd32621d84700fb573fe17e0b91 now that `0.21.2` has been released.
> Revert "Revert "Bump bitflags to 2.0""

- Cargo.lock
- examples/bpf_query/Cargo.toml
- examples/bpf_query/src/main.rs
- libbpf-rs/src/query.rs
NOTE: this is totally API-breaking, but the initial API wasn't really useful.
This avoids allocation overhead and guessing by reading the values and re-invoking the system call. Each array is blocked by a feature flag from the iterator.
Here's an example program using iced-x86 to disassembly the jited code:
```
use iced_x86::Formatter;
fn main() {
for prog in libbpf_rs::query::ProgInfoIter::default().include_jited_prog_insns(true) {
let mut d = iced_x86::Decoder::new(32, &prog.jited_prog_insns, 0);
let mut f = iced_x86::GasFormatter::new();
while d.can_decode() {
let insn = d.decode();
let mut f_insn = String::new();
f.format(&insn, &mut f_insn);
println!("{}", f_insn);
}
}
}
```
> libbpf-rs: optionally return full vecs from query

- examples/bpf_query/src/main.rs
- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/query.rs
- libbpf-rs/src/util.rs
This change addresses a few remaining issues of #269 and adds a `CHANGELOG` entry.
> Add CHANGELOG entry for #269

- libbpf-cargo/src/gen/mod.rs
- libbpf-rs/src/object.rs
- libbpf-rs/tests/test.rs
By stashing an opts struct internally and converting name from a String to a CString, we can return a reference to an opt struct. This allows us to stack the lifetimes so that we don't need to copy-paste the name_ptr logic everywhere we call it.
The motivation for doing this was so that I could do the same for pin_root_path without adding another 3 copies of the name implementation.
> libbpf-rs: Change ObjectBuilder opts semantics

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/link.rs
It seems as if `Link` objects (`bpf_link`) are fine to send across thread boundaries. Mark the type as `Send` accordingly.
Fixes: #546
> Implement Send for Link

- .github/dependabot.yml
- .github/workflows/audit.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
Update `actions/checkout` GitHub Action to the most recently released version `v4`.
> Update `actions/checkout` GitHub Action to v4

- .github/workflows/test.yml
Let's depended on `Swatinem/rust-cache@v2` instead of `Swatinem/rust-cache@v2.2.0`. The former gets automatically bumped when a new release is cut, which is more convenient than having a pull request created every time (though it comes at the cost of being less obvious).
> Use `Swatinem/rust-cache@v2`

- libbpf-rs/src/btf/mod.rs
Because most of the btf files that come with the kernel are in raw format, the btf from_path function needs to support parsing btf files in raw format. In addition, the load_vmlinux_btf function is added, which is very convenient and does not need to manually specify the btf path.
Thanks!
> Support parsing btf files in raw format and add load_vmlinux_btf function 

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/btf/mod.rs
- libbpf-rs/src/lib.rs
- libbpf-rs/src/link.rs
- libbpf-rs/src/linker.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/object.rs
- libbpf-rs/src/perf_buffer.rs
- libbpf-rs/src/print.rs
- libbpf-rs/src/program.rs
- libbpf-rs/src/ringbuf.rs
- libbpf-rs/src/skeleton.rs
- libbpf-rs/tests/test.rs
`libbpf-rs` aims to be a convenient but thin wrapper around `libbpf` functionality. Not all functionality provided of `libbpf` is exposed through its API. This can quickly become a blocker if, say, some getter is not hooked up, but the value required to perform an operation. In the spirit of being a thin wrapper, it makes sense for us to provide access to the underlying `libbpf` objects. When nothing else is available, these can be used directly in conjunction with `libbpf-sys` to, effectively, write Rust-syntax C code.
So far we have provided very ad-hoc accessor methods for retrieving pointers to the underlying `libbpf` objects. With this change we formalize this approach some more, by introducing the `AsLibbpfObject` trait and implementing it for major `libbpf-rs` types.
Using a trait …
> Introduce AsRawLibbpf trait

- .github/workflows/test.yml
- Cargo.lock
- examples/bpf_query/Cargo.toml
- examples/tc_port_whitelist/Cargo.toml
- examples/tproxy/Cargo.toml
- examples/tproxy/src/bin/proxy.rs
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/Cargo.toml
- libbpf-cargo/README.md
- libbpf-rs/CHANGELOG.md
- libbpf-rs/Cargo.toml
- libbpf-rs/README.md
Update the nix dependency that we depend on to 0.27, to prevent copies of multiple versions being pulled in during the build.
> Update nix dependency to 0.27

- Cargo.lock
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/lib.rs
The `Error` enumeration in `libbpf-cargo` doesn't really serve any meaningful purposes at this point: sure, it helps users differentiate between build and generation errors, but the difference arguably has no semantic significance that is worth preserving. On top of that, users can always invoke `build()` and `generate()` instead of `build_and_generate()` to have literally the same information at their finger tips.
Remove the `Error` type in favor of just exposing a `anyhow::Error`, which is probably the most flexible.
> Remove `Error` enumeration from libbpf-cargo

- examples/capable/src/main.rs
- examples/runqslower/src/main.rs
- examples/tproxy/src/main.rs
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/test.rs
- libbpf-rs/src/skeleton.rs
Respin of https://github.com/libbpf/libbpf-rs/pull/611.
> Fix up some mutability warts on datasec skeleton accessors (take #2)

- libbpf-rs/src/map.rs
Clippy suggests the usage of the vec! macro instead of manually creating an object and resizing it [0]. Follow the suggestion.
[0] https://rust-lang.github.io/rust-clippy/master/index.html#/slow_vector_initialization
> Incorporate clippy reported suggestion

- .github/workflows/publish.yml
- .github/workflows/test.yml
- libbpf-rs/tests/test.rs
The `actions-rs/toolchain` GitHub action is no longer maintained. Switch over to using `dtolnay/rust-toolchain` in its stead.
> Replace deprecated actions-rs/toolchain usage

- libbpf-cargo/src/build.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/lib.rs
- libbpf-cargo/src/main.rs
- libbpf-rs/src/btf/mod.rs
- libbpf-rs/src/btf/types.rs
- libbpf-rs/src/lib.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/object.rs
- libbpf-rs/src/perf_buffer.rs
- libbpf-rs/src/print.rs
- libbpf-rs/src/program.rs
- libbpf-rs/src/query.rs
- libbpf-rs/src/ringbuf.rs
- libbpf-rs/src/tc.rs
- libbpf-rs/src/util.rs
In the past we had many submissions that, for one reason or another, were using absolute paths to functions/constants in a very inconsistent manner. It is not particularly great use of anybody's time pointing these out and it's certainly a job that computers can do better. Clippy folks seem to concur that this can be a useful lint [0] and we got blessed with clippy::absolute_paths.
Enable it throughout libbpf-rs and libbpf-cargo and fix all violations.
[0] https://github.com/rust-lang/rust-clippy/issues/10568
> Enable clippy::absolute_paths lint

- libbpf-rs/src/map.rs
- libbpf-rs/tests/test.rs
> libbpf-rs: add support for bpf_map_update_batch method

- libbpf-rs/src/error.rs
For (better? or) worse the EINTR error is typically treated somewhat specially by clients. As such, it seems reasonable for us to expose it properly as opposed to just capturing it as "other".
Introduce the `ErrorKind::Interrupted` variant to allow for that.
> Introduce ErrorKind::Interrupted variant

- libbpf-cargo/src/build.rs
On those architectures, libbpf expects different values than reported by std::env::const::ARCH, causing a build failure as follows:
```console
0: Command `clang -I/builddir/build/BUILD/crypto-auditing-agent-0.2.1/target/rpm/build/crypto-auditing-agent-b76cca1d0cfd3630/out -fno-stack-protector -D__TARGET_ARCH_powerpc64 -g -O2 -target bpf -c /builddir/build/BUILD/crypto-auditing-agent-0.2.1/src/bpf/audit.bpf.c -o /tmp/.tmpwsWurL/audit.o` failed (exit status: 1)
1: In file included from /builddir/build/BUILD/crypto-auditing-agent-0.2.1/src/bpf/audit.bpf.c:6:
/usr/include/bpf/usdt.bpf.h:83:13: error: Must specify a BPF target arch via __TARGET_ARCH_xxx
83 |                 long ip = PT_REGS_IP(ctx);
|                           ^
/usr/include/bpf/bpf_tracing.h:576:26: note: expanded from macro …
```
> libbpf-cargo: fix inference of __TARGET_ARCH_ on ppc64le and s390x

- libbpf-cargo/src/main.rs
Commit 4ef150551dbb ("Enable clippy::absolute_paths lint") wrongly added the clippy::absolute_paths lint to the allow list in libbpf-cargo. Warn about it instead, as had been the intention.
> libbpf-cargo: Warn on clippy::absolute_paths

- libbpf-rs/src/object.rs
- libbpf-rs/tests/test.rs
If map auto creation was disabled, the Object would fail to load since the map's underlying fd will be -1.
This checks the if the map autocreate flag was disabled and skips creating a Map for it.
> libbpf-rs: handle maps that were autocreate(false)

- .github/dependabot.yml
In the past we have hit a case where two Rust package update PRs were merged and that resulted in a merge conflict that wasn't detected by either change. Since then we have done some "@dependabot rebase; @dependabot merge" dance.
Let's just limit the number of outstanding PRs to a single one, to serialize creation completely.
> Limit Depandabot Cargo lock file updates to one PR

- .github/workflows/test.yml
- Cargo.lock
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/Cargo.toml
- libbpf-cargo/README.md
- libbpf-rs/CHANGELOG.md
- libbpf-rs/Cargo.toml
- libbpf-rs/README.md
This change overhauls the crate's feature set. The 'novendor' feature violates Cargo's "features should be additive" rule [0]. It has been made a no-op in libbpf-sys starting with 1.3.0. With this change we remove it from this crate altogether. We introduce the 'vendored' feature, which causes all library dependencies to be built from vendored source code. We preserve the current default, which is using a vendored copy of libbpf but relying on system libelf and zlib, because while it would be great to be self-contained, the additional build tools required to build said libraries makes this a no-go.
[0] https://doc.rust-lang.org/cargo/reference/features.html
> Overhaul feature set

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/build.rs
- libbpf-rs/CHANGELOG.md
Similar to what we did for libbpf-rs itself with commit 291c6a4e0368 ("Overhaul feature set"), remove the novendor feature in favor of having a disableable default feature.
> libbpf-cargo: Remove novendor feature

- libbpf-rs/src/error.rs
The `ok_or_invalid_input()` and `ok_or_unexpected_eof()` methods of the `IntoError` trait aren't actually used by the crate (anymore). Current versions of Rust lament this fact.
Remove them to make the toolchain happy.
> Remove unneeded IntoError trait methods

- .github/workflows/test.yml
- Cargo.lock
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/Cargo.toml
- libbpf-cargo/README.md
- libbpf-rs/CHANGELOG.md
- libbpf-rs/Cargo.toml
- libbpf-rs/README.md
While I am a big fan of minimizing dependencies, disabling a bunch of default features of clap results in a sub-par user experience. Keep default features enabled.
> libbpf-cargo: Enable default features of clap

- examples/capable/build.rs
- examples/runqslower/build.rs
- examples/tc_port_whitelist/build.rs
- examples/tproxy/build.rs
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/build.rs
- libbpf-cargo/src/lib.rs
- libbpf-cargo/src/main.rs
- libbpf-cargo/src/make.rs
- libbpf-cargo/src/test.rs
> libbpf-cargo: Stop treating clang arguments as a string

- libbpf-cargo/src/gen/mod.rs
An error message such as
> Error: Failed to generate skeleton for libbpf-rs/examples/runqslower/src/bpf/runqslower.bpf.c
>
> Caused by:
>     No such file or directory (os error 2)
is misleading and nonsensical, given that runqslower.bpf.c exists. Report a proper causal chain to make errors like this at least somewhat actionable.
> libbpf-cargo: Report proper error chain on missing object file

- examples/capable/src/main.rs
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
Certain Rust types that we use in our generated skeleton are not valid for all bit patterns. Bools, for example, are defined to be one byte in size, but their representation allows only for 0 and 1 values to be used in said byte -- everything else is undefined behavior. Enums have similar problems, in that not the entire space of the backing type is necessarily used by variants.
The result is an unsoundness issue in our generated skeletons, because C code could accidentally set an enum to an invalid value and Rust code would exhibit undefined behavior.
This change fixes this problem by wrapping the corresponding attributes in MaybeUninit. In so doing users have to be explicit when accessing them and make sure that the current representation is indeed valid.
Closes: #589
> libbpf-cargo: Wrap generated "unsafe" type in MaybeUninit

- libbpf-cargo/src/gen/mod.rs
De-duplicate open & open_opts in generated SkelBuilder by...calling one from the other.
> libbpf-cargo: De-duplicate open & open_opts in generated SkelBuilder

- examples/capable/src/main.rs
- examples/runqslower/src/main.rs
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/test.rs
- libbpf-rs/src/skeleton.rs
When a type is present in more than one section in the ELF binary (e.g., in .bss as well as .rodata), the generation code ends up generating multiple Rust correspondents as well. That is horrible for interoperability, because there is no language-level connection between these types and so the corresponding objects are not interchangeable in any way.
This change fixes this problem by putting all generated types in a single Rust module, '<project>_types', as opposed to having them be emitted into modules for each of the "data sections".
> Stop generation of duplicate types

- libbpf-rs/src/btf/mod.rs
- libbpf-rs/src/iter.rs
- libbpf-rs/src/link.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/object.rs
- libbpf-rs/src/perf_buffer.rs
- libbpf-rs/src/print.rs
- libbpf-rs/src/program.rs
- libbpf-rs/src/query.rs
- libbpf-rs/src/ringbuf.rs
- libbpf-rs/src/skeleton.rs
- libbpf-rs/src/tc.rs
- libbpf-rs/src/util.rs
Use declarations such as those for `crate::libbpf_sys` serve no purpose, because the crate is already known globally. Remove them and similar ones, such as for `std::boxed::Box`, which is in the prelude and, hence, available automatically.
> Remove unnecessary imports

- .github/workflows/test.yml
When Dependabot creates a pull request we always end up with two CI runs -- one for the pull request and one for the push of the commit to a branch.
Exclude pushes to branches for Dependabot created pull requests, to prevent this duplication of work.
> Exclude Dependabot created branches from CI testing on push

- examples/bpf_query/src/main.rs
- libbpf-rs/src/query.rs
The `recursion_misses` statistic is incremented under two scenarios when BPF stats are enabled:
1. When recursion is detected within a BPF program execution. In such a case, the recursive execution is prevented, thus incrementing the recursion_misses counter.
2. When a kprobe handler tries to execute a BPF program and the kernel finds that another program is already running on the CPU. 
These increments help track instances where BPF program execution is skipped due to recursion or concurrent execution prevention mechanisms.
This PR exposes this counter in the ProgramInfo struct. I'd like to add it to [bpftop](https://github.com/Netflix/bpftop)
> Add recursion_misses field to ProgramInfo struct

- libbpf-rs/src/btf/types.rs
We have some redundant imports in test modules that were not flagged by earlier version of rustc. Remove them so that once we upgrade we don't see any warnings/errors.
> Remove a bunch of redundant imports

- libbpf-rs/src/util.rs
Since `libbpf_get_error` always returns negative error code, it should be **inverted** before passing in `Error::from_raw_os_error`.
> fix: pass negative error code to Error::from_raw_os_error

- libbpf-rs/tests/test.rs
Enable the `clippy::absolute_paths` lint in the test module.
> Enable clippy::absolute_paths lint in test module

- libbpf-cargo/src/build.rs
- libbpf-cargo/src/test.rs
Recent versions of clippy warn about the lack of specification of the truncation behavior when open a file for writing with create(true) [0]. With this change we make sure to call truncate(true) alongside to silence the resulting warning.
[0] https://rust-lang.github.io/rust-clippy/master/index.html#suspicious_open_options
> Specify truncation behavior when "creating" files

- libbpf-rs/CHANGELOG.md
Add a CHANGELOG entry for #692, which added support for attaching to ksyscall handlers.
> Add CHANGELOG entry for #692

- examples/capable/README.md
- libbpf-rs/src/map.rs
Switch to using the parse_ret_i32() helper in one more location, instead of having to hard code the condition evaluation there "by hand".
> Use parse_ret_i32() helper in one more location

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/mod.rs
It's possible to run into borrow checker conflicts with the generated datasec accessor functions. The reason for that is that they all borrow from the very same skeleton object and so once one of the borrows is mutable, no other borrows may exist.
Yet, in reality each datasec object is backed by strictly distinct regions of memory and so there is no actual conflict. However, we haven't found a way to convey this property to the Rust borrow checker given current language features, other than falling back to runtime checking (there are proposals floating around for annotating method signatures with the members they borrow, which would allow the borrow checker to reason correctly, but they are not stable by any means).
With this change we take a way out in the form of exposing the "raw" …
> libbpf-cargo: Add "raw" datasec accessors

- Cargo.lock
- libbpf-rs/Cargo.toml
- libbpf-rs/src/print.rs
- libbpf-rs/src/util.rs
std::sync::OnceLock has been stabilized in rust version 1.70.  [std::sync::LazyLock](https://github.com/rust-lang/rust/issues/109736) is not stable yet. Implement LazyLock with std::sync::OnceLock as an alternative to std::sync::LazyLock.
> Remove lazy_static dependency

- libbpf-cargo/src/gen/mod.rs
There is no need to return an owned object from
`canonicalize_internal_map_name()`. Work with a statically allocated one.
> Return static string from canonicalize_internal_map_name()

- Cargo.lock
- libbpf-rs/Cargo.toml
Update the `serial_test` dev-dependency to version `3.0` to get the latest and greatest.
> Update serial_test dev-dependency to 3.0

- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-rs/src/btf/types.rs
Change three small bits:
- don't duplicate "Invalid type" reporting logic
- refine "Failed to generate skeleton" to differentiate two locations
- fix typo in some comment
> Three minor changes

- libbpf-cargo/src/gen/btf.rs
Improve the fidelity of errors reported by `GenBtf::required_padding()` by including current and required offset in message.
> libbpf-cargo: Improve error for GenBtf::required_padding() method

- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
Adjust the logic in `GenBtf::type_declaration()` to correctly handle forward declarations. That is generally useful, but will needed particularly for struct_ops shadow type support.
> Correctly handle forward declarations in GenBtf::type_declaration()

- examples/tcp_ca/Cargo.toml
Enable default features for the clap dependency of the tcp-ca example. See commit 20fd30cb8b8f ("libbpf-cargo: Enable default features of clap") for reasoning.
> Enable default features for clap dependency of tcp-ca example

- libbpf-cargo/src/gen/btf.rs
Factor out a new free-standing function, type_default(), that generates the "default" of a Rust type represented by the given BTF type.
> libbpf-cargo: Make type_default() a free-standing function

- libbpf-cargo/src/gen/btf.rs
Factor out a new free-standing function, is_struct_packed(), checks whether a given BTF type was declared as "packed".
> libbpf-cargo: Make is_struct_packed() a free-standing function

- libbpf-rs/src/print.rs
When using libbpf-sys' bindgen feature, the generated va_list type varies on different platforms.
Use void pointer as va_list pointer type and transmute pointer of type use va_list pointer instead for cross platform support.
See https://github.com/rust-lang/rust-bindgen/issues/2631
> Avoid using generated va_list type

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/program.rs
OpenProgram is not really different from Program and so it should implement the AsRawLibbpf trait just the same.
> Implement AsRawLibbpf for OpenProgram

- Cargo.lock
- Cargo.toml
- examples/tcp_ca/src/bpf/tcp_ca.bpf.c
- examples/tcp_ca/src/main.rs
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/test.rs
This pull request adds support for struct_ops shadow objects to the generated skeletons. These allow for the pre-load modifications of fields in a struct_ops object.
To make that happen we add a new generated struct_ops type that holds pointers to all the known struct_ops objects and allows for modification of their values before final load.
> Add `struct_ops` shadow object support

- examples/capable/build.rs
- examples/capable/src/main.rs
- examples/runqslower/build.rs
- examples/runqslower/src/main.rs
- examples/tc_port_whitelist/build.rs
- examples/tc_port_whitelist/src/main.rs
- examples/tproxy/build.rs
- examples/tproxy/src/main.rs
Do what commit 545c59c006eb ("Adjust tcp_ca example to produce skeleton in example directory") started for all the remaining example and have the skeletons created in the respective src/bpf/ directory to make them easier discoverable.
> Adjust remaining examples to produce skeleton in src/bpf/ directory

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/test.rs
This change adds support for handling of custom .data sections, declared via SEC(".data.xxxx") in the BPF C code. It makes sure that we generate the corresponding Rust types as well as the proper maps getters.
> libbpf-cargo: Add support for custom .data sections

- libbpf-cargo/src/gen/mod.rs
commit 51ffd0f added support for custom sections.
this broke skeleton generation when bpf_printk() was used along with BPF_NO_GLOBAL_DATA, as e.g. the map '.rodata.str1.1' contains invalid chars. add simple escaping to the map name as well (similar to the one used for the section name)
> libbpf-cargo: escape map names

- libbpf-cargo/README.md
- libbpf-rs/README.md
The CI badges we have in the README files no longer point to valid data. Update them as per the latest.
> Fix CI badges in README

- .github/workflows/test.yml
- examples/capable/src/main.rs
- examples/runqslower/src/main.rs
- examples/tcp_ca/src/main.rs
- examples/tproxy/src/main.rs
- libbpf-rs/src/btf/types.rs
- libbpf-rs/src/xdp.rs
- libbpf-rs/tests/test.rs
- libbpf-rs/tests/test_print.rs
I tried setting the "StdExternalCrate" 'group_imports' rustfmt configuration. It works, but it has some not-so-great impacts as well. Nevertheless, there are some uncontroversial suggestions in there, so keep them. Also make sure to not exclusively run rustfmt on only libbpf-rs and libbpf-cargo, but also also examples in CI.
> Fix a couple of formatting glitches

- Cargo.lock
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/build.rs
- libbpf-cargo/src/gen/mod.rs
The crate already depends on libbpf as an integral building block. Yet, it pulls in its own version of libbpf-sys.
Switch to just consuming libbpf-rs's re-export, which reduces the maintenance burden by having a single point of update, while also potentially making it easier to replace/patch the libbpf-sys version in use.
> libbpf-cargo: Eliminate direct libbpf-sys dependency

- libbpf-rs/src/lib.rs
All items in the "High level workflow" are labeled #1. While they appear correct in the rendered documentation, it is confusing when reading the source code.
Number them correctly.
> Properly number high-level workflow items

- examples/tcp_ca/Cargo.toml
- examples/tcp_ca/src/main.rs
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/mod.rs
Our generated skeletons hardcode the libbpf-rs dependency to use. That is fine in principle, but it can be limiting for users. For example, a user may legitimately want to import libbpf-rs under a different name, in which case skeletons simply won't work. Or, instead of having a direct dependency on libbpf-rs they may want to rely on a re-export through a different dependency.
Currently there is no way to cater to these cases. With this change we introduce an escape hatch that allows for such usage. Specifically, we generate a super::* import that optionally pulls in items defined in the outer module. It should be extremely unlikely that this pulls in any conflicting items, because this should only honor 'pub'. In any event, conflicts can always be mitigated by introducing an intermediary …
> libbpf-cargo: Add support for "import injection" to generated skeletons

- deny.toml
- vmlinux/Cargo.toml
Recent runs of the Audit workflow failed, citing a missing license of the vmlinux crate. At this point we don't intend to publish it or shit it and it really is only meant to be used as a dev-dependency. Mark the crate as unpublishable in its Cargo.toml and instruct cargo-deny to ignore such crates in its evaluation.
> Fix Audit workflow

- deny.toml
> Address a bunch of `cargo-deny` deprecation warnings

- libbpf-cargo/src/gen/mod.rs
Allow the `clippy::absolute_paths` lint so that references to items specified by absolute path are not flagged, if this lint is enabled in client code.
> libbpf-cargo: Allow absolute path usage in generated skeleton

- .github/workflows/test.yml
- examples/capable/src/main.rs
- examples/runqslower/src/main.rs
- examples/tc_port_whitelist/src/main.rs
Deny the `absolute_paths` Clippy lint project wide in CI, to enforce a more coherent style in an automated fashion.
> Flag absolute path usage in CI

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/lib.rs
- libbpf-rs/src/user_ringbuf.rs
Add a CHANGELOG entry for pull request #776, which added support for user ring buffers to the library. Also make sure to export UserRingBufferSample publicly to reduce friction when working with it.
> Add CHANGELOG entry for #776

- libbpf-rs/src/user_ringbuf.rs
The recent addition of user ring buffers included calls to `*libc::__errno_location()`.
Apart from requiring an unsafe block, this function might not be available on some targets, such as Android, causing build failures.
Use the portable implementation provided by `std::io::Error::last_os_error` instead.
> Remove unsafe and platform dependent errno retrieval

- Cargo.lock
- examples/tc_port_whitelist/Cargo.toml
- libbpf-cargo/Cargo.toml
- libbpf-rs/Cargo.toml
- libbpf-rs/src/btf/mod.rs
- libbpf-rs/src/btf/types.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/program.rs
- libbpf-rs/src/query.rs
Hello! 
I am using `libbpf-rs` in one of my personal projects and I noticed that I was pulling in `toml-edit` via `libbpf-rs` which accounted for 1.3 seconds of my total build time. With the help of `cargo tree` I realized that `num_enum` is pulling in that dependency (and many others!) and I decided to try to remove it from `libbpf-rs` completely. Let me know what you think!
`cargo udeps` also noticed some extra things that can be removed, so I went ahead and removed those.
> Remove dependency on `num_enum`.

- libbpf-rs/src/lib.rs
- libbpf-rs/src/map.rs
Export the MapKeyIter type as part of the public interface. The type itself has always been public, it just couldn't be named. Improve ergonomics and documentation by exporting it properly.
> Export MapKeyIter in public interface

- Cargo.lock
- examples/bpf_query/src/main.rs
- libbpf-rs/CHANGELOG.md
- libbpf-rs/Cargo.toml
- libbpf-rs/src/map.rs
- libbpf-rs/src/program.rs
Remove the strum_macros dependency. Having arbitrary Display implementations for enum types makes very little sense and is generally not recommended practice. Drop the derive and just use the Debug representation where needed.
> Remove strum_macros dependency

- .github/workflows/test.yml
- Cargo.lock
- libbpf-rs/Cargo.toml
- libbpf-rs/tests/test.rs
- libbpf-rs/tests/test_tc.rs
- libbpf-rs/tests/test_xdp.rs
The way we specify the tests to run as root is non-obvious and error-prone: we just include "sudo" inside a tests name and then filter for that when running.
The test_tag crate provides first class support for tagging of tests, which makes what is going on a bit more obvious. Switch over to using it.
> Use test-tag crate for tagging root tests

- Cargo.lock
- examples/bpf_query/src/main.rs
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
- libbpf-rs/CHANGELOG.md
- libbpf-rs/Cargo.toml
- libbpf-rs/src/map.rs
- libbpf-rs/src/program.rs
When we pad structs to ensure proper alignment, we may end up generating
padding arrays of more than 32 byte when alignment is large. In such
cases, Rust would not be able to derive a Default and we'd need to make
sure to generate one ourselves, or a compilation error will ensue.
With this change we make sure to switch over to generating a Default
impl ourselves in those cases.
> libbpf-cargo: Generate Default impl on overly large padding

- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-rs/src/btf/mod.rs
Provide a proper Debug impl for the Btf type, that basically dumps all types contained in it. Having this kind of functionality available makes it easier to understand problems. Also, implement Debug for the internal GenBtf type to be able to quicker debug problems.
> Provided a proper Debug impl for Btf type

- libbpf-rs/tests/test.rs
We probably shouldn't be sharing the same target name for the static probes created in the USDT tests, if for no other reason than it being stupidly confusing. Rename one of them.
> Use different target names in USDT tests

- libbpf-cargo/src/gen/mod.rs
There is seemingly no need for the gen_bpf_object_iter macro to work with a mutable bpf_object pointer. Use a const one instead and simplify a bunch of code in the process.
> Adjust gen_bpf_object_iter to use const* bpf_object

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/test.rs
Generate Rust correspondents for the types used in BPF maps. Having these types generated will eliminate the need for miscellaneous hacks to be employed to get the corresponding Rust types by other means.
Closes: #602
> Generate Rust types for types used in BPF maps

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/object.rs
Add an implementation of AsRawLibbpf for OpenObject. We already have one for Object, and both types just encapsulate a bpf_object pointer.
> Implement AsRawLibbpf for OpenObject

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/object.rs
- libbpf-rs/src/program.rs
It seems questionable for the OpenProgram type to eagerly retrieve the program's section. For one, that member seems useful in only very niche situations, meaning that we may perform unnecessary work. Handling is also different from other similar members such as the program's name, which is retrieve on-demand only. Lastly, initializing this member eagerly (i.e., in the constructor), means that we add an unnecessary fallible path to every call site using an object of the type. Just move the section retrieval into the OpenProgram::section() member function.
> Retrieve OpenProgram::section lazily

- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/btf/mod.rs
- libbpf-rs/src/btf/types.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/object.rs
- libbpf-rs/src/program.rs
The fact that we are interfacing with C APIs and working with NUL terminated strings is more or less an implementation detail. OsStr is at least somewhat easier to use compared to CStr and so it is both more ergonomic and more flexible to expose it in public APIs. Switch everything over.
> Remove CStr usage from API surface

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/object.rs
- libbpf-rs/src/program.rs
Remove the 'name' and 'section' members of the Program type, replacing them with methods that directly inquire the data in a lossless fashion.
> Remove 'name' and 'section' member of Program

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/map.rs
- libbpf-rs/src/object.rs
- libbpf-rs/tests/test.rs
The constraint that a MapHandle's name is a String is overly strong: we have decided earlier that OpenMap, for example, works with OsStr. Switch MapHandle's name to an OsString to mirror this contract.
> Make MapHandle::name an OsString

- libbpf-rs/src/map.rs
We don't need to use the unsafe std::mem::zeroed() usage for initializing a bpf_map_info object when it implements Default. Just use it instead else we do in other locations as well.
> Remove unnecessary unsafe code usage

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/map.rs
It appears as if the setting of the inner map file descriptor is a fallible operation. Make sure to check and convey the result.
> Adjust OpenMap::set_inner_map_fd() to return Result

- examples/tc_port_whitelist/src/main.rs
- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/lib.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/object.rs
- libbpf-rs/src/perf_buffer.rs
- libbpf-rs/src/ringbuf.rs
- libbpf-rs/src/user_ringbuf.rs
- libbpf-rs/tests/test.rs
This change reworks our BPF map abstractions somewhat. Specifically, we remove the MapHandle part from a Map. These two are more or less separate concepts and having one Deref into the other, while perhaps convenient, is somewhat confusing. Perhaps more importantly, it leads to a bunch of shenanigans, such as:
- Map creation being a fallible operation, despite a properly created bpf_map being provided already
- Map objects effectively carrying heaps of duplicated information: the file descriptor, map type, key size and value size are all already contained in the additionally stored bpf_map object
- the existence of the conceptually unnecessary MapFd enum
- the arbitrary difference in implementation between OpenMap (only bpf_map pointer) and Map (bpf_map pointer + handle) versus …
> Introduce MapCore trait

- .rustfmt.toml
- libbpf-cargo/src/lib.rs
- libbpf-rs/src/btf/mod.rs
- libbpf-rs/src/lib.rs
- libbpf-rs/src/map.rs
- libbpf-rs/src/program.rs
- libbpf-rs/src/skeleton.rs
- libbpf-rs/src/util.rs
It turns out `rustfmt` can ensure a consistent comment length by applying automatic wrapping. Let's enable the functionality to get some more consistency into the code base and ensure that pull requests adhere to a basic standard in the process.
Also set a two other options that don't exactly change anything at this point but are nice to have and give us more flexibility in the future.
> Let rustfmt take care of wrapping comments

- libbpf-cargo/src/gen/mod.rs
- libbpf-rs/src/skeleton.rs
Rename the 'a lifetime used extensively in the skeleton logic to something at least a tad more meaningful.
> Rename 'a lifetime

- libbpf-cargo/src/gen/mod.rs
- libbpf-rs/src/skeleton.rs
There isn't really a point in having a method that does nothing more than return a pointer require a mutable receiver -- ultimately it is up to the caller what is being done with the pointer anyway, and casting pointer mutability is a trivial (and safe) operation. Hence, adjust ObjectSkeletonConfig::prog_link_ptr() to work on a shared receiver and remove ObjectSkeletonConfig::map_mmap_ptr_mut() in favor of map_mmap_ptr(), which now returns a mutable pointer.
> Simplify ObjectSkeletonConfig pointer accessor methods

- libbpf-cargo/src/gen/mod.rs
- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/object.rs
ObjectBuilder is really just a thin wrapper around libbpf's bpf_object_open_opts and bpf_object__open_file()/bpf_object__open_mem(). As such, it makes sense for us to make that a bit more obvious by implementing the AsRawLibbpf trait.
> Implement AsRawLibbpf for ObjectBuilder

- libbpf-cargo/src/gen/mod.rs
- libbpf-rs/src/skeleton.rs
Add an implementation of the AsRawLibbpf trait for ObjectSkeletonConfig, which really is a fairly thin wrapper around libbpf's bpf_object_skeleton type.
> Implement AsRawLibbpf for ObjectSkeletonConfig

- libbpf-rs/src/skeleton.rs
Unclear why we need a bunch of boxes everywhere. It appears all we want is storage for a pointer. Gotta love the indirection.
> Remove a bunch of unnecessary (??) boxes

- libbpf-cargo/src/gen/mod.rs
- libbpf-rs/src/skeleton.rs
No point in having a public accessor for some member that may or may not be set and whose initialization happens entirely external to the object itself via a bunch of unsafe hackery. It's less than useful, it's actively confusing. Remove it.
> Remove ObjectSkeletonConfig::object_ptr()

- libbpf-rs/tests/common/mod.rs
- libbpf-rs/tests/test.rs
- libbpf-rs/tests/test_tc.rs
- libbpf-rs/tests/test_xdp.rs
Heaps of our tests run multiple times, because test_tc and test_xdp use the test module, and with that pull in the tests it defines. Introduce a proper module with common functionality to fix this.
> Introduce a proper test utility module

- libbpf-rs/tests/common/mod.rs
- libbpf-rs/tests/test.rs
- libbpf-rs/tests/test_tc.rs
- libbpf-rs/tests/test_xdp.rs
Now that we have a module for sharing test helper functionality, move the get_map() and get_prog() helper into it and use them from more places.
> Use get_*() helper functions in other test modules

- libbpf-rs/src/query.rs
This data was previously accessible, but was maybe inadvertently made private when be857ed landed. This patch makes the data accessible again by marking `Tag`s inner field as `pub`.
Closes #842
> Mark `Tag`'s inner data as `pub`

- libbpf-rs/CHANGELOG.md
Add a CHANGELOG entry for pull request #843, which made the inner contents of `query::Tag` publicly accessible.
> Add CHANGELOG entry for #843

- libbpf-rs/tests/bpf_object_regen.sh
It seems that the path to the x86 vmlinux.h file as specified in bpf_object_regen.sh is no longer accurate. Adjust it to match reality.
> Fix default vmlinux.h path

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/object.rs
- libbpf-rs/tests/test.rs
Mirror what map and program APIs do and return an OsStr from OpenObject::name(). Also introduce Object::name() for consistency.
> Adjust OpenObject::name() to return Option<&OsStr>

- libbpf-cargo/src/gen/mod.rs
As part of commit a8a4503d9cbb ("Remove
ObjectSkeletonConfig::object_ptr()") we started clearing the object pointer from the C skeleton object. That does not appear to work properly. Revert that part of the change.
> libbpf-cargo: Don't clear skeleton object pointer

- .github/workflows/test.yml
It appears we have literally not a single test exercising the skeleton generate, build, and test workflow end-to-end.
Add a CI workflow running the tcp_ca example to have some kind of coverage.
> Add CI job running tcp_ca example

- libbpf-rs/CHANGELOG.md
Add another CHANGELOG item for pull request #854, which also adjusted the SkelBuilder::open() and OpenSkel::load() methods to require mutable reference to storage space for a BPF object.
> Add another CHANGELOG item for #854

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/program.rs
A bunch of the setters on OpenProgram can fail only when the program is loaded already. We encode the fact that a program is loaded via the type system and any OpenProgram should never be loaded. As such, adjust the return types of these setters accordingly, making the methods infallible.
> Removed Result return type from OpenProgram setters

- examples/capable/src/main.rs
- examples/runqslower/src/main.rs
- examples/tc_port_whitelist/src/main.rs
- examples/tcp_ca/src/main.rs
- examples/tcp_option/src/main.rs
- examples/tproxy/src/main.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/test.rs
- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/object.rs
- libbpf-rs/src/skeleton.rs
We strictly speaking only need storage for a single BPF object for use with a skeleton, but currently we pass in such space to both the SkelBuilder::open() and OpenSkel::load() methods. The main reason for this decision was that we didn't want to make the assumption that OpenObject and Object have the same size. However, we are already doing something similar for the {Open,}{Program,Map} types. As such, this change adjusts OpenSkel::load() to no longer require an object reference to be passed in and modifies the skeleton generation logic to just reuse the already provided storage space instead.
> Adjust OpenSkel::load() to reuse earlier BPF object storage

- libbpf-rs/src/btf/mod.rs
The type ID 0 is defined to map to void. It doesn't really matter whether or not we include it in the Debug output for the Btf type, as it can be argued that it's always there anyway and that's "common knowledge" (haha...).
Be that as it may, it's confusing to see some iteration starting at ID 0 while most start with ID 1. Stick to what is more commonly done and start with ID 1, for uniformity.
> Adjust Btf Debug impl to start dumping at ID 1

- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
No pointer in being overly verbose and repeat type names everywhere. Just reference Self instead.
> libbpf-cargo: Reference Self instead of spelling out the name

- examples/capable/src/main.rs
- examples/runqslower/src/main.rs
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/test.rs
Instead of calling the module into which Rust types are emitted '<skeleton>_types' just call it 'types'. There isn't really a good reason for the former naming from what I can tell. Client code will always be able to prevent naming conflicts, because it is free to include the generated skeleton inside its own module. In fact, that's what all our examples do:
> mod capable {
>     include!(concat!(
>         env!("CARGO_MANIFEST_DIR"),
>         "/src/bpf/capable.skel.rs"
>     ));
> }
> use capable::capable_types::uniqueness;
In the above snippet, the usage of capable::capable_types is a needless repetition.
> libbpf-cargo: Emit Rust types into 'types' module

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/btf/types.rs
Implement the Copy & Clone traits for various BTF types, as they are all guaranteed to be cheaply copyable.
> Implement Copy for various BTF types

- libbpf-cargo/src/gen/mod.rs
It appears as if the allowance of the clippy::transmute_ptr_to_ref lint in the generated skeletons is no longer necessary. Remove it.
> libbpf-cargo: Remove clippy::transmute_ptr_to_ref allowance

- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/test.rs
Introduce the GenStructOps helper type, taking over parts of the GenBtf::struct_ops_type_definition() method.
> libbpf-cargo: Introduce GenStructOps helper type

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/test.rs
The struct_ops type is basically a libbpf-cargo construct -- there is no corresponding C type to be found in the BTF information (there is something similar in the C skeleton, but that is entirely orthogonal). However, because we generate this type inside the types module, which is the dumping ground for all Rust types with C equivalents, there is the potential for conflicts. For example, the kernel actually does have a type called struct_ops itself. That is not currently a problem, but it may become one once we generate Rust types for more of the C ones present in BTF.
To fix this issue, move the generated struct_ops type out of the types module and into the "global" (from the skeleton's view) namespace. Also rename it to StructOps as an indication that this is a Rust construct without a …
> libbpf-cargo: Move generated struct_ops type out of types module

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/gen/mod.rs
Adjust the skeleton code to just generate Rust types for types present in the BTF of the object file being used. There is no real reason to artificially restrict types, as the BTF itself is already heavily trimmed down by the generation infrastructure. Yet, making all types present in it available to Rust users can reduce friction in usage, as everything that is available in C will be available in Rust as well.
Closes: #603
> libbpf-cargo: Generate Rust types for all BTF types

- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
Contents of the .ksyms section are special in that they can actually lead to invalid code generation in both C and Rust, caused by it containing multiple variables of the same name and type. While the on-disk BTF seems valid and not suffering from this problem, once loaded through libbpf it appears that the contained types get patched up to duplicates.
Work around the issue by not dumping .ksym contents. Yikes.
> libbpf-cargo: Don't generate Rust types for .ksyms contents

- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
It turns out just rawifying reserved identifiers as done commit 77cc68cc5684 ("libbpf-cargo: Make sure to escape reserve keywords used for identifiers") is not enough. Some of those identifiers are not allowed to be used, even in raw form.
For those, modify them instead of "escaping". Yes, that can result in a collision, but it seems rather unlikely and it's unclear what else we can do.
> libbpf-cargo: Treat special identifiers...specially

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/program.rs
- libbpf-rs/tests/test.rs
Add a CHANGELOG entry for pull request #890, which adjust the ProgramInput's context_in field to a mutable reference.
> Add CHANGELOG entry for #890

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/ringbuf.rs
When we build up a RingBuffer object via the RingBufferBuilder::build() function, we may leak memory on error paths, because of the usage of raw pointers.
Fix the issue by:
1) stop converting boxes into raw pointers to begin with, which should
be fine given that libbpf does not actually dereference the sample
callback pointer in ring_buffer__new() or ring_buffer__add().
2) properly freeing the ring buffer if we return early because we failed
to successfully add a callback.
Closes: #862
> Fix potential memory leaks in RingBufferBuilder::build()

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/mod.rs
With the switch over to using uninitialized memory that has been provided to the skeleton at open time we ended up leaking the object. The reason is simple: on paper we no longer own it and neither does the MaybeUninit that was passed in. As a result, nobody runs its destructor.
> libbpf-cargo: Fix leakage of bpf_object

- .github/workflows/test.yml
Make sure to run our tcp_ca example with leak sanitizer enabled, so as to catch any potential memory leaks in the skeleton generation logic.
> Run tcp_ca example with leak sanitizer enabled

- libbpf-rs/src/program.rs
The slice_from_array function declared inside ProgramMut::test_run() is, well, private to the function. Hence, it makes little sense to slab on a visibility specifier. Remove it.
> Remove unnecessary pub(crate) visibility specifier

- libbpf-cargo/src/gen/mod.rs
Improve the panic message we see when failing datasec mmap pointer retrieval to make it a bit more obvious what went wrong.
Refs: #909
> libbpf-cargo: Improve panic message for datasec mmap ptr retrieval

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/mod.rs
The .kconfig section is special in that libbpf sets its values as part of the load procedure. That means that until then, i.e., during open, contents are invalid. To that end the library doesn't even set the mmap pointer to anything but NULL, despite all heuristics pointing at it being mmapable and whatnot.
That's a problem for us, because we generate section contents and attempt to have them reference this nonexistent mmap area, which will fail.
Work around the issue by special casing this section and not permitting direct datasec access. If users require this access they have to manually iterate maps, retrieve initial value, and cast it to types::kconfig.
Closes: #909
> libbpf-cargo: Don't populate datasec contents for kconfig map

- libbpf-cargo/src/gen/mod.rs
In the past we wrote the fully qualified syntax for usage of the libbpf_rs::AsRawLibbpf trait inside the generated skeletons. We don't need to do that: given that we are in a custom module, it is safe for us to just import the trait.
> libbpf-cargo: Explicitly import libbpf_rs::AsRawLibbpf trait

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/mod.rs
With the changes to initialize maps inline during skeleton open/load, we may end up with Clippy complaining that a loop never loops or a match never matches, if there are no maps present.
Silence the warnings. Such patterns are to be expected in generated code like this.
> libbpf-cargo: Suppress some Clippy warnings

- Cargo.toml
- examples/bpf_query/Cargo.toml
- examples/capable/Cargo.toml
- examples/runqslower/Cargo.toml
- examples/tc_port_whitelist/Cargo.toml
- examples/tcp_ca/Cargo.toml
- examples/tcp_option/Cargo.toml
- examples/tproxy/Cargo.toml
- libbpf-cargo/Cargo.toml
- libbpf-rs/Cargo.toml
- vmlinux/Cargo.toml
As it turns out Cargo now allows us to define certain Cargo meta-data in a workspace-wide manner and then more easily reuse that. We intend to update things such as the edition for all crates in the workspace and the version of the two crates being published from the repository should always be kept in sync. This makes those properties (and others) perfect candidates for this infrastructure.
With this change we switch over to using workspace-wide properties for a bunch of meta-data.
> Use workspace-wide definitions for various meta-data

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/program.rs
- libbpf-rs/src/util.rs
- libbpf-rs/tests/test.rs
After an eBPF program is loaded to the kernel and the loader process 
exits, a user may want to attach this program to PROG_ARRAY
of another one. This pull request adds a function to get a file
descriptor based on a pin file and guarantees that it represents a
program. Later, this descriptor can be used to be added to the
`PROG_ARRAY` or for creating an `XDP` program handle.
> program: add get_fd_by_pin() api

- libbpf-rs/src/util.rs
Use a proper temporary file inside the object_type_from_fd() test, instead of relying on the temporary directory being /tmp/ and hard coding that fact.
> Use proper temporary file in object_type_from_fd() test

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/mod.rs
In the logic we generate for opening the skeleton, we unconditionally work with some bpf_object_open_opts object, even if the user did not customize anything. That's fine in principle, but it can trigger a bug when a old system libbpf is used and which violates its forward compatibility guarantees.
With this change we work around the issue by invoking the bpf_object__open_skeleton() libbpf function with a NULL pointer if SkelBuilder::open() instead of SkelBuilder::open_opts() is being used. This is generally the common case and so we work around the underlying libbpf bug until fixed and new releases rolled out to various distributions.
Closes: #927
> libbpf-cargo: Open skeleton without options by default

- Cargo.lock
- Cargo.toml
- libbpf-cargo/CHANGELOG.md
- libbpf-rs/CHANGELOG.md
Prepare for release of 0.24.4 by bumping both libbpf-rs and libbpf-cargo versions accordingly.
> Release 0.24.4

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/program.rs
- libbpf-rs/tests/test.rs
Rename Program::get_id_by_fd() to id_from_fd(). The "by" terminology is weird at best and seems to make little grammatical sense. Keep the former around as deprecated until the next minor version bump.
> Rename Program::get_id_by_fd() to id_from_fd()

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/program.rs
- libbpf-rs/tests/test.rs
Rename Program::get_fd_by_id() to fd_from_id(). The "by" terminology is weird at best and seems to make little grammatical sense. Keep the former around as deprecated until the next minor version bump.
> Rename Program::get_fd_by_id() to fd_from_id()

- libbpf-cargo/src/gen/btf.rs
Incorporate a suggestion that clippy in Rust 1.81 makes about using a character array in a String::replace call.
> Incorporate clippy suggestion

- libbpf-rs/src/perf_buffer.rs
This PR introduces a flexible and generic implementation for `PerfBufferBuilder` to support any type that implements the `MapCore` and `AsFd` traits, rather than being restricted to a specific `Map` type. 
Currently, `PerfBufferBuilder` is limited to a specific `Map` type, which restricts its usability with other types that implement the required traits. This update increases the extensibility of the `PerfBufferBuilder` and allows developers to use it with a wider variety of map-like structures. For example, a scenario that uses a pinning map.
> feat(perf_buffer): perf_buffer relies on traits rather than specific type

- libbpf-rs/src/perf_buffer.rs
We don't need to require MapCore + AsFd bounds, because MapCore already implies AsFd by its very definition. Simplify the code by removing the + AsFd part.
> Remove duplicate AsFd bounds from PerfBufferBuilder

- libbpf-rs/CHANGELOG.md
Add a CHANGELOG entry for pull request #939, which adjusted the PerfBufferBuilder type to work with anything implementing the MapCore trait instead of strictly requiring a Map object.
> Add CHANGELOG entry for #939

- libbpf-rs/src/link.rs
This is a small fix that marks Link with `must_use`, as discussed in #940. This makes it clear right away that the program will detach immediately if not used.
> Mark link with must_use

- examples/tcp_option/src/main.rs
- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/program.rs
- libbpf-rs/tests/test.rs
Attaching a BPF program currently provides exclusive access to the Program object, but it's not exactly clear why that is. Given that libbpf work on const pointers, let's switch over to having those methods work on a shared receiver instead, eliminating a bunch of possible borrow conflicts.
Refs: #953
> Make various Program::attach_* methods work on shared receiver

- Cargo.lock
- Cargo.toml
- libbpf-rs/CHANGELOG.md
Prepare for release of 0.24.5 by bumping both libbpf-rs and libbpf-cargo versions accordingly.
> Release 0.24.5

- libbpf-cargo/src/build.rs
This commit updates the __TARGET_ARCH_xx define to match what is used in bpf_tracing.h.
Reference https://github.com/torvalds/linux/blob/8cf0b93919e13d1e8d4466eb4080a4c4d9d66d7b/tools/lib/bpf/bpf_tracing.h#L8-L38
> Fix __TARGET_ARCH_xx define for riscv64,loongarch64,sparc64,mips64

- libbpf-rs/build.rs
For testing purposes, libbpf-rs also maintains a build script that can be used to generate files necessary for running the test suite. Port over commit 704543e256db ("Use runtime CARGO_CFG_TARGET_ARCH in build-script") as well as commit abc9eeb56fd7 ("Fix __TARGET_ARCH_xx define for riscv64,loongarch64,sparc64,mips64") from libbpf-cargo to libbpf-rs' build script.
> Port recent libbpf-cargo build.rs changes to libbpf-rs

- libbpf-cargo/CHANGELOG.md
Add a CHANGELOG entry for pull request #959, which fixed the CARGO_CFG_TARGET_ARCH environment variable query from a build script in a cross-compilation context.
> Add CHANGELOG entry for #959

- .github/workflows/publish.yml
Make sure to use the `--fail-with-body` option in our special-sauce `curl` invocation inside the publish CI workflow, to ensure that errors are bubbled up properly.
> Properly fail publish CI workflow on error

- Cargo.lock
- Cargo.toml
- libbpf-cargo/CHANGELOG.md
Prepare for release of 0.24.6 by bumping both libbpf-rs and libbpf-cargo versions accordingly.
> Release 0.24.6

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
- libbpf-rs/src/btf/types.rs
This was noticed because a "vmlinux.h" contained:
```
struct bio {
...
union {};
...
};
```
Which caused the following error when trying to use "struct bio" in a .bpf.c file:
```
thread 'main' panicked at /home/jrc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libbpf-cargo-0.24.6/src/gen/btf.rs:769:49:
index out of bounds: the len is 0 but the index is 0
```
Fix this by hiding empty unions from the generated types. Rust does not allow union types with zero fields.
Fixes #974.
> libbpf-cargo: Handle empty unions in BTF types

- Cargo.lock
- libbpf-cargo/Cargo.toml
Update the dependency on `goblin` from 0.6 to 0.9.
The trivial use of this crate in a test for `libbpf-cargo` is not affected by any of the [documented breaking changes](https://github.com/m4b/goblin/blob/master/CHANGELOG.md) between these releases.
Furthermore, running `cargo test` in `libbpf-cargo/` still works.
> Update goblin dependency to 0.9

- Cargo.lock
- Cargo.toml
- libbpf-cargo/CHANGELOG.md
Prepare for release of 0.24.7 by bumping both libbpf-rs and libbpf-cargo versions accordingly.
> Release 0.24.7

- examples/netfilter_blocklist/src/bpf/netfilter_blocklist.bpf.c
- libbpf-rs/CHANGELOG.md
- libbpf-rs/tests/bin/src/netfilter.bpf.c
- libbpf-rs/tests/test_netfilter.rs
Add a CHANGELOG entry for pull request #980, which added support for attaching to netfilter hooks. Also fix a few minor things that slipped through review and remove tests for one more hook which is not available on a local system and causing test failures because of it.
> Add CHANGELOG entry for #980

- libbpf-rs/src/map.rs
Fix the rendering of the documentation of MapCore::update_batch() method, whose 'keys' and 'values' descriptions contained wrong markdown.
> Fix documentation of MapCore::update_batch()

- libbpf-rs/src/map.rs
Remove some unnecessary casts. It's unclear why the compiler/linter would not flag that.
> Remove unnecessary casts

- libbpf-rs/src/query.rs
- libbpf-rs/tests/test.rs
Newer versions of Clippy report a couple of warnings. Address them.
> Eliminate a couple of Clippy warnings

- libbpf-rs/src/map.rs
Similar to commit 62130a056fae ("Fix documentation of MapCore::update_batch()"), fix the rendering of the documentation of MapCore::delete_batch() method, whose 'keys' description contained wrong markdown.
> Fix documentation of MapCore::delete_batch()

- Cargo.lock
- Cargo.toml
- libbpf-rs/CHANGELOG.md
Prepare for release of 0.24.8 by bumping both libbpf-rs and libbpf-cargo versions accordingly.
> Release 0.24.8

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
Rather than generating Rust enums from C enums, which might not be correct, as for example, C allows enum variants to share a value while Rust does not.
This fixes #982.
Test Plan
=========
Verified that tests pass in CI in my fork and that my project compiles fine and works will with this change.
> libbpf-cargo: Generate C enums as custom types with const fields

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/test.rs
Fix the CHANGELOG entry for pull request #989 and convert the compilation test to a proper end-to-end style one going all the way from C code to buildable Rust project.
> Apply a few changes to #989

- examples/capable/src/main.rs
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
In the past C enums were mapped to Rust enums in the generated skeletons. Because Rust enums enums have stricter requirements than C ones, we have to wrap them in MaybeUninit (see 87929fff0d9d ("libbpf-cargo: Wrap generated "unsafe" types in MaybeUninit")).
With the switch to using regular constants for representing these C enums in Rust as done in commit e24198391c0a ("libbpf-cargo: Generate C enums as custom types with const fields"), we no longer have to treat them as "unsafe" and can remove the MaybeUninit wrapper.
> libbpf-cargo: Stop treating C enums as "unsafe"

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/map.rs
Add a few fixes on top of pull request #996. Among others, remove an 'as' cast which may have been unsound, remove some other unnecessary ones, and don't repeat code needlessly.
> Add a few changes for #996

- libbpf-cargo/src/lib.rs
Warn about lack of Debug impls on publicly exposed types, similar to what we have been doing in libbpf-rs ever since commit f9479934d66e ("libbpf-rs: add warn(missing_debug_implementations) to lib.rs").
> libbpf-cargo: Warn on missing Debug impls

- libbpf-cargo/src/build.rs
- libbpf-cargo/src/gen/mod.rs
Restrict the visibility of some functions and types currently declared public for seemingly no apparent reason.
> libbpf-cargo: Restrict visibility of some functions/types

- libbpf-cargo/src/build.rs
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/lib.rs
- libbpf-cargo/src/main.rs
- libbpf-cargo/src/metadata.rs
- libbpf-cargo/src/test.rs
It goes against every Cargo project preconception to have certain module be compiled from both lib.rs and main.rs and it leads to shenanigans such as #[allow(dead_code)] tags scattered all over the place, which is its own can of worms when done at such a high level. Do it properly and export necessary functionality. To prevent any misconceptions of there being a stable API contract for functionality *only* being used by the binary, put it into an hidden module.
> libbpf-cargo: Clean up crate-structure mess

- libbpf-cargo/src/build.rs
- libbpf-cargo/src/lib.rs
Update `build_and_generate` to return a `CompilationOutput` owning the stderr
of the compiler process. This gives consumers access to the stderr to output as
they see fit.
Provides a `stderr` method that calls `String::from_utf8_lossy`. The primary
consumer is `sched-ext/scx` which outputs each line with
`println!("cargo:warning={}", l)`, showing the warnings quite nicely in the
Cargo output when there isn't an error.
Test plan:
- Pointed that Cargo.lock at this repo and built.
> libbpf-cargo: return stderr from clang

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/build.rs
Add a CHANGELOG entry for #994, which introduced the CompilationOutput type to libbpf-cargo and made SkeletonBuilder::build* methods return in on success.
> Add CHANGELOG entry for #994

- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
With the switch from emitting C enums as Rust enums to mapping them to Rust struct instead, we dropped the PartialEq and Eq derives. Add them back to make working with these generated types more convenient.
> libbpf-cargo: Implement PartialEq for generated Rust "enums"

- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
With the switch from emitting C enums as Rust enums to mapping them to Rust structs instead, we no longer allow access to the underlying integer. That's a bit of a usability snag, because it forces users to fall back to transmuting constants just to get a hold of the inner value.
Expose the inner value publicly to make that easier.
> libbpf-cargo: Expose inner Rust "enum" values publicly

- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/Cargo.toml
- libbpf-cargo/README.md
- libbpf-rs/CHANGELOG.md
- libbpf-rs/README.md
Prepare for release of `0.25.0-beta.0` by bumping both libbpf-rs and libbpf-cargo versions accordingly.
> Release 0.25.0-beta.0

- libbpf-rs/src/object.rs
https://github.com/libbpf/libbpf-rs/issues/1027
> Implement Send and Sync for OpenObject

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/object.rs
Add a CHANGELOG entry for pull request #1028, which added Send + Sync bounds to the OpenObject and Object types. Also add missing SAFETY comments.
> Add CHANGELOG entry for #1028

- .github/workflows/test.yml
Leak sanitizer infrastructure in Rust is badly broken [0]. Disable it until it resembles something of a working piece of software again.
[0] https://github.com/rust-lang/rust/issues/111073
> Disable LeakSanitizer tests

- .github/workflows/test.yml
Update the Clang version used when running tests in CI. To make that happen, bump the Ubuntu base image in use as well. We need something more recent than Clang 14 to have proper enum64 support [0].
[0] https://github.com/libbpf/libbpf-rs/pull/1035
> Update CI ubuntu image and clang version

- Cargo.lock
- Cargo.toml
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/Cargo.toml
- libbpf-cargo/README.md
- libbpf-rs/CHANGELOG.md
- libbpf-rs/README.md
Prepare for release of 0.25.0-beta.1 by bumping both libbpf-rs and libbpf-cargo versions accordingly.
> Release 0.25.0-beta.1

- .github/workflows/test.yml
Ubuntu can't get their act together and provide reliably accessible servers. Make the repeatedly failing jobs optional for the time being.
> Make ARM builds optional in CI

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/link.rs
Implement Sync for Link. The only operations that can be performed on a &Link are pin_path() and detach(), neither of which modify the object. pin_path() just reads an attribute and detach() performs a system call with the link's file descriptor. Hence, Sync should be fine to implement for Link.
> Implement Sync for Link

- .github/workflows/test.yml
We don't need "recommended" packages to be installed in CI, but that's what apt-get chooses to do by default. Provide the --no-install-recommends option to prevent this from happening.
> Stop installing recommended packages in CI

- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/lib.rs
The 'debug' argument passed to `gen_skel_contents()` is unused; removed it and adjust callers accordingly.
> libbpf-cargo: Remove unused 'debug' argument

- Cargo.lock
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/build.rs
- libbpf-cargo/src/lib.rs
- libbpf-cargo/src/main.rs
- libbpf-cargo/src/make.rs
- libbpf-cargo/src/test.rs
Remove the logic for checking the clang version in use. This logic is worrisome and insufficient for a couple of reasons.
It is insufficient, because we don't actually know what clang version we require -- that is a moving target. Nobody is actively testing against the lowest supported clang version to make sure that our stuff actually works with it. At this point, the stated minimum of `10.0.0` is also increasingly unlikely to be found in the wild, rendering the check less and less useful with every passing year. Ultimately, if a necessary feature really is not available, one would hope that the emitted error isn't too cryptic for anybody to make sense of it.
On the "worrisome" front, the over reliance on anything and everything clang (not just with this check, but with naming more …
> libbpf-cargo: Remove clang version check logic

- Cargo.lock
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/build.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/lib.rs
- libbpf-cargo/src/main.rs
- libbpf-cargo/src/make.rs
- libbpf-cargo/src/metadata.rs
- libbpf-cargo/src/test.rs
We support a very limited form of logging by printing certain actions happening when the --debug option is provided. While not particularly useful at the current stage, this is probably functionality worth keeping in the long run.
However, the current implementation is questionable at best: we plumb through some boolean flag everywhere, which convolutes various call sites and requires potentially excessive changes to support emitting a new log message somewhere.
With this change we switch over to using proper logging based on the log crate and other parts of the ecosystem. As a result, we get support for multiple log levels, proper time stamping, limited output coloring, and additional filtering capabilities via environment variables. At the same time, we remove usage of flags that have …
> libbpf-cargo: Add proper logging infrastructure

- .github/workflows/test.yml
Our Arm jobs have been failing for a while. At first that was sporadic (in retrospect likely because we got runners sporting different images due to staged rollout of a new Ubuntu version) and now its permanent. The cause of the failure seems to be some change in format of their sources.list, causing us to no longer be able to no longer fetch necessary package lists. I haven't found a guide in their documentation how to properly update, so roll back to a known good distro version until somebody has the nerves to deal with this %#&*($&#*($.
> Downgrade Ubuntu version for Arm testing

- .github/workflows/test.yml
We just fixed out Arm tests with commit 2ce495438856 ("Downgrade Ubuntu version for Arm testing"). Hence, there is no need for said tests to be optional anymore. Revert the commit making them so.
This reverts commit 271afc86ce55bb51369437b6a00219329a6d70f2.
> Revert "Make ARM builds optional in CI"

- libbpf-cargo/src/build.rs
- libbpf-cargo/src/lib.rs
- libbpf-cargo/src/main.rs
- libbpf-cargo/src/make.rs
- libbpf-cargo/src/test.rs
Please see individual commits for descriptions. This is internal logic only at this point.
> Add support for compiling BPF object file from multiple input files

- libbpf-rs/src/map.rs
Remove the 'missing_docs' lint annotation from OpenMap impl, as it is no longer required.
> Remove 'missing_docs' lint annotation from OpenMap impl

- libbpf-rs/tests/test.rs
Remove two unnecessary `#[allow(clippy::needless_update)]` annotations.
> Remove two unnecessary `#[allow(clippy::needless_update)]`

- libbpf-rs/src/map.rs
- libbpf-rs/tests/test.rs
My use case is:
1. Read map's max_entries before loading, and resize max_entries according to some logic.
2. After map is loaded, access resized max_entries for logging etc.
For the sake of completeness I added `max_entries` on `MapCore` and implemented on `MapHandle` too, although I don't use this flow (I can add just on `Map` instead, or instead implement it with `bpf_obj_get_info_by_fd` to avoid increasing the struct's size)
> map: Add max_entries() for Map objects

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/map.rs
- libbpf-rs/tests/test.rs
Add a CHANGELOG entry for pull request #1064, which added the max_entries() getter to various map types. Also improve on a few minor details that did not justify another round trip.
> Add CHANGELOG entry for #1064

- libbpf-cargo/src/build.rs
- libbpf-cargo/src/test.rs
The `build_btf_mmap()` function is almost comically complex in what it does. In order to compile a single `.bpf.c` file it creates an entire Cargo Rust project and builds that, instead of simply compiling the file directly. Now that we have the `BpfObjBuilder` type, we can just about accomplish the latter without jumping through dozens of hoops. Do it. As a pleasant side effect of this reduction in complexity, the `btf_dump` test runtime more than halves:
Before:
```
$ time target/debug/deps/libbpf_cargo-37cf1fde780326f7 btf_dump
> running 34 tests
> [...]
> ________________________________________________________
> Executed in    2.09 secs    fish           external
```
After:
```
$ time target/debug/deps/libbpf_cargo-37cf1fde780326f7 btf_dump
> running 34 tests
> [...]
> …
```
> libbpf-cargo: Simplify build_btf_mmap() test helper

- libbpf-cargo/src/test.rs
Usage of clang as the compiler is the default for the SkeletonBuilder type. Hence, there is no need to instruct it to use this compiler explicitly.
> Remove unnecessary 'clang' setting

- libbpf-cargo/src/gen/mod.rs
We have seen several lints get renamed or removed over time. Our generated skeletons explicitly allow a couple of lints and these may be affected by such changes as well. To make that less of an event, silently allow the usage of renamed lints down there.
> libbpf-cargo: Allow renamed lint usage in skeleton

- libbpf-cargo/src/build.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/main.rs
- libbpf-cargo/src/make.rs
- libbpf-cargo/src/metadata.rs
It makes no sense to pass around `Option<&PathBuf>` object: `Option<&Path>`
is more flexible on each axis. Switch to using the latter.
> libbpf-cargo: Stop working with Option<&PathBuf>

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
Our `SkeletonBuilder` currently only support building a skeleton from a single `.bpf.c` file. However, users may very well compile multiple `.bpf.c` files into `.bpf.o` and link them into a single object. In such a scenario, it is easily possible that we end up with multiple types of the same name in the corresponding BTF. Currently, this results in compilation errors.
With this change we handle this case more gracefully, by enumerating these types, similar to what libbpf does in its dumping logic.
> libbpf-cargo: Handle duplicated types in BTF more gracefully

- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/Cargo.toml
- libbpf-cargo/README.md
- libbpf-rs/README.md
- libbpf-rs/dev/Cargo.toml
- libbpf-rs/src/util.rs
Update the `cargo_metadata` dependency to version `0.19.1`, in order to get the latest and greatest.
> libbpf-cargo: Update cargo_metadata to 0.19.1

- .github/workflows/test.yml
GitHub Actions comes with an auto-merge feature, which allows for automatically merging PRs once certain requirements are met. For us, these requirements would be the passing of all CI checks. Alas, their !@#*&()$&@!(#* configuration requires us to explicitly list all CI jobs that need to pass, which is an absolute maintenance nightmare. To improve on the situation at least somewhat, introduce a job that captures all required checks, so that the definition of this arbitrary entity is at least co-located with the definition of these jobs and not hidden behind four layers of clicky-bunti UI fluff.
The logic is adapted from:
https://github.com/orgs/community/discussions/75568#discussioncomment-10351973
> Introduce required-checks CI job

- examples/capable/Cargo.toml
- examples/netfilter_blocklist/Cargo.toml
- examples/runqslower/Cargo.toml
- examples/tc_port_whitelist/Cargo.toml
- examples/tcp_ca/Cargo.toml
- examples/tcp_option/Cargo.toml
- examples/tcp_option/src/main.rs
- examples/tproxy/Cargo.toml
The vmlinux crate isn't really versioned as such, as the only compatibility guarantee provided is that git history won't be clobbered. There is also no intention of publishing it.
As such, there is no point in specifying a version -- the SHA1 pinning the git commit is sufficient. Remove any version specifications.
> Stop specifying version for vmlinux dependency

- libbpf-rs/src/ringbuf.rs
It's not non-zero - it's negative error values. The error is also propagated (which is important if translated to Result), so document that as well.
> ringbuf: Fix callback docs

- examples/bpf_query/src/main.rs
The BPF prog disassemble output seems incorrect compared to bpftool. 
Change the bitness to 64 fix this.
> examples/bpf_query: Fix disassemble output

- Cargo.lock
- libbpf-rs/Cargo.toml
- libbpf-rs/src/program.rs
- libbpf-rs/tests/common/mod.rs
- libbpf-rs/tests/test.rs
Change UprobeOpts::func_name to Option<String> 
so that user can attach uprobe to specifc offset in binary. 
This would be useful for target that have symbol stripped.
> libbpf-rs: Make func_name optional for uprobe attach

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/program.rs
Add a CHANGELOG entry for pull request #1096, which adjusted the `UprobeOpts::func_name member` to be an Option. Also improve the documentation for the same slightly, by covering the `None` case.
> Add CHANGELOG entry for #1096

- libbpf-rs/src/program.rs
Add binding for `bpf_program__set_autoattach` as discussed in #1085 . 
`bpf_program__set_autoattach` is of type `void`. So, no return checks are needed. 
Thanks to @mmullin-halcyon
> add: binding for `set_autoattach`

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/program.rs
Add a CHANGELOG entry for pull request #1106, which added the `OpenProgramMut::set_autoattach()` functionality.
> Add CHANGELOG entry for #1106

- libbpf-rs/src/map.rs
Missing doc for ringbuf, stack_trace and cgroup_array map types. Added `#[allow(missing_docs)]` in the respective types.
> add doc in map.rs

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/error.rs
- libbpf-rs/src/lib.rs
- libbpf-rs/src/program.rs
- libbpf-rs/tests/bin/src/kprobe.bpf.c
- libbpf-rs/tests/test.rs
The following variants are added to attach a program:
- Kprobe multi, with and without providing additional options.
- Kprobe with additional options.
- Raw tracepoint with addition options.
The main motivation is 1) kprobe multi has significant performance benefits and 2) using additional options allows to use BPF cookies in probes.
In addition tests for raw tracepoints are added (for the existing support and for the new variant added), as well as basic tests for all kprobe variants (excluding kretprobes).
A few things to note wrt. to reviews:
- `attach_kprobe_with_opts` kept the `kretprobe` flag as an argument even though it is part of the underlying `libbpf-sys` options struct. It felt more natural IMO to keep this flag visible and in sync with the normal kprobe API, but this can be …
> Add a few program attach variants

- libbpf-rs/CHANGELOG.md
Add a CHANGELOG entry or pull request #1119, which bumped the libbpf-sys dependency and added new program attach type variants.
> Add CHANGELOG entry for #1119

- libbpf-rs/src/program.rs
- libbpf-rs/tests/test.rs
The attach_kprobe helper has a kretprobe boolean as a first argument and then the target name. The attach_kprobe_multi helper has similar arguments, but in the inverse order. Reorder them to make the API consistent.
This shouldn't break production software as the kprobe multi support isn't part of an official release yet.
> Make attach_kprobe_multi consistent with attach_kprobe

- libbpf-rs/src/query.rs
Unify the documentation comment style that we use in `query.rs`, by terminating all sentences with a period for the sake of consistency.
> Unify documentation comment style in `query.rs`

- examples/bpf_query/src/main.rs
- libbpf-rs/src/query.rs
We have moved to the libbpf-sys v1.5. Added sockmap link type now. 
Perf-event link type was missed in the previous pr.
> libbpf-rs: add missing link types

- libbpf-rs/CHANGELOG.md
Add a CHANGELOG entry for pull request #1127, which added additional variants to the query::LinkTypeInfo enumeration available in libbpf-sys 1.5.0.
> Add CHANGELOG entry for #1127

- libbpf-rs/CHANGELOG.md
Add a CHANGELOG entry for pull request #1114, which introduced the `TracepointCategory` enumeration.
> Add CHANGELOG entry for #1114

- libbpf-cargo/Cargo.toml
There is no reason for us to depend on env_logger 0.11.6 or higher specifically, anything from the 0.11 branch will do. Relax the version constraint.
> libbpf-cargo: Relax env_logger version constraint

- libbpf-cargo/Cargo.toml
There is no reason for us to depend on log 0.4.25 or higher specifically, anything from the 0.4 branch will do. Relax the version constraint.
> libbpf-cargo: Relax log version constraint

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/lib.rs
- libbpf-rs/src/program.rs
In order to easily provide the ability to attach cookies to perf events, add a hook for libbf's bpf_program__attach_perf_event_opts.
> libbpf-rs: add attach_perf_event_with_opts hook

- .github/workflows/test.yml
Ubuntu requires us to run `apt-get update` before being able to expect successful package installation, so do that.
> Run apt-get update before installing packages in CI

- libbpf-cargo/src/gen/btf.rs
- libbpf-rs/src/btf/mod.rs
- libbpf-rs/src/query.rs
clippy compalined here: https://github.com/libbpf/libbpf-rs/actions/runs/14391135733/job/40358223316
> libbpf-rs: minor fixes suggested by linter

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/program.rs
- libbpf-rs/tests/bin/src/run_prog.bpf.c
- libbpf-rs/tests/test.rs
The former, when non-zero, is used to run the program `repeat` times. The latter is the number of ns a run took on average.
A test was added to confirm the behaviour. The program bumps a counter, said counter is verified to match `repeat`.
> libbpf-rs: Add suport for repeat and duration in Program{Input,Output}

- libbpf-rs/CHANGELOG.md
Cap line length consistently and don't terminate lines with periods for consistency.
> Reformat CHANGELOG a bit

- examples/capable/src/main.rs
- examples/ringbuf_multi/src/main.rs
- examples/runqslower/src/main.rs
- examples/tcp_ca/src/main.rs
- examples/tcp_option/src/main.rs
- examples/tproxy/src/main.rs
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/test.rs
> libbpf-cargo: Make all XXX_data skeleton members optional

- libbpf-rs/dev/build.rs
As of Rust 1.74, the std::io::Error::other() helper exists as a short hand for std::io::Error::new(std::io::ErrorKind::Other, ...) construct. With recent versions of Rust, usage of this method is now suggested by Clippy [0].
Switch over to using it.
[0]: https://rust-lang.github.io/rust-clippy/master/index.html#io_other_error
> Use std::io::Error::other() helper

- libbpf-rs/src/skeleton.rs
Rename the ProgSkelConfig::p member to prog, in an attempt to make the name somewhat more meaningful.
> libbpf-cargo: Rename ProgSkelConfig::p member to prog

- libbpf-rs/src/skeleton.rs
Rename the ObjectSkeletonConfigBuilder::p member to obj, in an attempt to make the name somewhat more meaningful.
> libbpf-cargo: Rename ObjectSkeletonConfigBuilder::p member to obj

- Cargo.lock
- libbpf-cargo/Cargo.toml
With version 1.5.0, libbpf has broken backwards compatibility, by requiring the bpf_map_skeleton.link member to be set to non-NULL [0] [1], segfaulting otherwise. This has since been fixed [2], but the maintainer has clarified that such breakage may happen again in the future and is in line with the unarticulated backwards compatibility contract.
Providing a stable interface on an unstable foundation like this is obviously impossible, generally speaking, as we can't anticipate what will break next. As such, we have to resort to restricting the set of supported libbpf(-sys) versions to known good ones. We do that on the libbpf-cargo front, as it's mostly the code gen APIs that are said to be at risk (though who knows...). Furthermore, we anticipate that 1.5.1, which is slated to arrive …
> libbpf-cargo: Restrict libbpf-sys versions we support

- Cargo.lock
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/build.rs
- libbpf-cargo/src/gen/mod.rs
- libbpf-cargo/src/main.rs
- libbpf-cargo/src/make.rs
- libbpf-cargo/src/metadata.rs
Commit 188522437ac9 ("libbpf-cargo: Add proper logging infrastructure") introduced a logging infrastructure to the crate that was based on the `log` crate. In the course of working more with it, it became more and more obvious that the restriction of being only ever able to set a single global logger is not particularly great for the use cases we may want to build.
The `tracing` crate does not have such a restriction, so switch over to using it instead.
```
$ cargo run -p libbpf-cargo -- libbpf make --manifest-path examples/capable/Cargo.toml --clang-args='-I~/.cargo/git/checkouts/vmlinux.h-280bd3e7fe8d89c0/8f91e9/include/x86/' -vvv
> [loads of output]
```
> libbpf-cargo: Use tracing crate instead of log

- libbpf-rs/CHANGELOG.md
- libbpf-rs/src/ringbuf.rs
- libbpf-rs/tests/test.rs
libbpf provides the ring_buffer__consume_n() API to consume up to a certain amount of items from ringbuffers [1].
Add the new method consume_raw_n() also in RingBuffer to provide the same functionality.
This is needed by sched_ext to allow user-space schedulers (based on scx_rustland_core) to selectively consume task items from BPF ring buffer [2].
[1] https://lore.kernel.org/bpf/20240406092005.92399-1-andrea.righi@canonical.com/
[2] https://github.com/sched-ext/scx/blob/ea361886f714b968092a1ea14bdee8330beb4d5f/rust/scx_rustland_core/assets/bpf.rs#L228
> RingBuffer: Introduce consume_raw_n()

- libbpf-cargo/src/gen/btf.rs
- libbpf-cargo/src/test.rs
Previously, anonymous types were named as __anon_{id} with id as a global counter. This approach caused cascading renaming of all subsequent anonymous definitions after any C anonymous struct order/amount change. This was a major design problem not for only development but even portability, since here may be the case when something was changed in vmlinux.h leading to compilation errors.
This PR addresses the issue by localizing cascading effects to the local struct layer rather than the global layer. While the solution is not fully ideal - cascading still occurs within individual structs - it eliminates the need for wide Rust code modifications when the order of anonymous struct definitions changes.
The PR is breaking and should be included in major version update.
The PR fixes #1161 …
> libbpf-cargo: Relative anonymous type naming for struct fields

- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/src/gen/btf.rs
Add a CHANGELOG entry for pull request #1178, which adjusted the naming of generated Rust types for anonymous C equivalents.
> Add CHANGELOG entry for #1178

- Cargo.lock
- Cargo.toml
- examples/btf_query/Cargo.toml
- examples/btf_query/src/main.rs
Introduce the `btf_query` example, illustrating how to query some properties of the vmlinux BTF information.
> Introduce btf_query example

- examples/capable/build.rs
- examples/runqslower/build.rs
Thank you for considering a contribution!
In order to streamline review experience for contributors and reviewers, please
be sure to *read* and *follow* the [Contributor's Guide][cont-guide]. It
lays out basic best practices, which, if followed will reduce unnecessary back
and forth and, ultimately, minimize the time it takes to get your change into
the library.
[cont-guide]: https://github.com/libbpf/libbpf-rs/blob/master/CONTRIBUTING.md
Add monitoring of related header files (*.h) in build.rs to trigger skeleton rebuilding when they are modified, not just when the BPF source (*.bpf.c) changes.
> Rebuild BPF skeleton when header files change

- Cargo.lock
- Cargo.toml
- examples/task_longrun/Cargo.toml
- examples/task_longrun/build.rs
- examples/task_longrun/src/bpf/task_longrun.bpf.c
- examples/task_longrun/src/bpf/task_longrun.h
- examples/task_longrun/src/main.rs
Cover [the BCC python binding](https://gist.github.com/danielocfb/a294ed6125ac2140d36cad2b6f67a8af) to Rust and libbpf-rs.
The BCC python binding output:
```bash
$ sudo python3 bcc-example.py
...
python3[65497] ran_for=326.51ms bt_seq=17
scheduler_tick
tick_sched_handle
tick_nohz_highres_handler
__hrtimer_run_queues
hrtimer_interrupt
__sysvec_apic_timer_interrupt
sysvec_apic_timer_interrupt
asm_sysvec_apic_timer_interrupt
scheduler_tick
tick_sched_handle
tick_nohz_highres_handler
__hrtimer_run_queues
hrtimer_interrupt
__sysvec_apic_timer_interrupt
sysvec_apic_timer_interrupt
asm_sysvec_apic_timer_interrupt
scheduler_tick
tick_sched_handle
tick_nohz_highres_handler
__hrtimer_run_queues
hrtimer_interrupt
__sysvec_apic_timer_interrupt
sysvec_apic_timer_interrupt …
```
> example: add task_perf example

- Cargo.lock
- libbpf-cargo/Cargo.toml
- libbpf-cargo/src/test.rs
libbpf-cargo has a large number of test strings for both input and generated code. IMO this makes the test file very hard to read, especially given my vim has a really hard time syntax highlighting it - it's unclear whether the 0 indented code is test code or part of the test's Rust.
Use `indoc!` to allow us to indent this test text as we see fit, allowing them to look like part of a test case instead of jumping back to 0 indentation. It's purely stylistic.
Test plan:
- `cargo test -p libbpf-cargo` - passed before, passes after, with the same number of tests.
- CI
Signed-off-by: Jake Hillion <jake@hillion.co.uk>
> libbpf-cargo: use indoc in test strings

- Cargo.lock
- Cargo.toml
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/Cargo.toml
- libbpf-cargo/README.md
- libbpf-rs/CHANGELOG.md
- libbpf-rs/README.md
Prepare for release of `0.26.0-beta.0` by bumping both libbpf-rs and libbpf-cargo versions accordingly.
> Release 0.26.0-beta.0

- libbpf-cargo/Cargo.toml
libbpf 1.6.1 seems fine to use with our library. Allow list it accordingly.
> libbpf-cargo: Allowlist libbpf-sys 1.6.1

- Cargo.lock
- Cargo.toml
- libbpf-cargo/CHANGELOG.md
- libbpf-cargo/Cargo.toml
- libbpf-cargo/README.md
- libbpf-rs/CHANGELOG.md
- libbpf-rs/README.md
Prepare for release of `0.26.0-beta.1` by bumping both `libbpf-rs` and `libbpf-cargo` versions accordingly.
> Release 0.26.0-beta.1

- libbpf-cargo/CHANGELOG.md
- libbpf-rs/CHANGELOG.md
The CHANGELOG entry for `0.26.0-beta.1` was for `libbpf-cargo`, not `libbpf-rs`. Fix it.
> Move 0.26.0-beta.1 CHANGELOG items

- .github/workflows/test.yml
- examples/capable/src/bpf/capable.bpf.c
- examples/runqslower/src/bpf/runqslower.bpf.c
- examples/task_longrun/src/bpf/task_longrun.bpf.c
- libbpf-rs/tests/bin/src/kprobe.bpf.c
- libbpf-rs/tests/bin/src/map_auto_pin.bpf.c
- libbpf-rs/tests/bin/src/percpu_map.bpf.c
- libbpf-rs/tests/bin/src/run_prog.bpf.c
- libbpf-rs/tests/bin/src/runqslower.bpf.c
- libbpf-rs/tests/bin/src/tracepoint.bpf.c
Run [bpflinter](https://github.com/d-e-s-o/bpflint/tree/main/cli) on all our .bpf.c files as part of CI and fix all pre-existing issues. Doing so should help us keep up with general BPF C coding pattern recommendations.
> Lint .bpf.c source code

- .github/workflows/test.yml
We are seeing CI failures of the 'clippy' job, due to the program supposedly not being installed. The reason seems to be that the underlying Ubuntu image stopped including the corresponding tool, and we never requested it explicitly.
Fix this problem by making sure we do install the program.
> Explicitly request 'clippy' component in CI workflow

- examples/bpf_query/src/main.rs
- libbpf-rs/src/link.rs
- libbpf-rs/src/query.rs
- libbpf-rs/tests/test.rs
heavily inspired by matching bpftool code
New PR created after https://github.com/libbpf/libbpf-rs/pull/1213 was closed due to staleness
> query: Support tracepoint & k(ret)probe in perf_event link infos
